### PR TITLE
Icon List Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
#### v0.1.0

- Add block

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel You also need to integrate ThemeIsle Icons as an option. Please see the updated code for the Button Group or Icons Block to see how.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani can you check [this file](https://github.com/Soare-Robert-Daniel/gutenberg-blocks/blob/icon-list-block/inc/css/blocks/class-icon-list-item-css.php): `/var/www/html/wp-content/plugins/otter-blocks/vendor/codeinwp/gutenberg-blocks/inc/css/blocks/class-cion-list-item-css`

I can't make the size of the icon to work.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Which icons? ThemeIsle or FontAwesome?

**Comment by Soare-Robert-Daniel** [comment]
both of them, they need to be selected by their HTML tag `i` or `svg`

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It doesn't work. I can't switch the icon libraries. If I click on ThemeIsle Icons, nothing happens.

**Comment by HardeepAsrani** [comment]
It doesn't look good on front. Can you take a look? @Soare-Robert-Daniel - sorry for the delay in replying, let's keep working on it regularly now.

Screen Shot 2020-12-17 at 12 02 11 AM
Screen Shot 2020-12-17 at 12 02 19 AM

**Comment by HardeepAsrani** [comment]
Hey @irinelenache - can you test this one? You will need to fix the vendor files in vendor/compose folder, like before.

**Comment by irinelenache** [comment]
@HardeepAsrani worked fine on my end, didn't find any problems

**Comment by HardeepAsrani** [comment]
Thank you @irinelenache.

@Soare-Robert-Daniel I made some changes, mostly regular, and merging this block. Once you come back, make sure to take a look at this commit to see how to handle split/merger of the block properly: https://github.com/Codeinwp/gutenberg-blocks/pull/464/commits/e9d028c70f235e9c2561d8df38d6105bebacd4cc

**Pull request merged**
