### PR TITLE
Fix icon list reset on refresh

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Reference: #664 

Problem: The icon list item is unaware if it already has an icon, so it will always take the parent's icon on refresh even though the correct icon is already saved.

~~Solution 1: The `hasCustomIcon` check if the icon is already defined instead of always initializing with `false`.~~

Solution 2: Remove the `hasCustomIcon` because of its faulty behavior. Now the parent icon list data is used only in creating new items. Once created, the item is independent of the changes in the parent.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Can you test @irinelenache to make sure icons aren't reset after page refresh in the editor?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel i get this errors when i switch to themeisle icons https://prnt.sc/12ua8y4

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, can you take a look @Soare-Robert-Daniel?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the problem is bizarre. The error indicated that some component is undefined. This error also happens on the parent icon list, but with a twist. It will output the error, but it does no crash and work normally.

I still not figured out where might be the error.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel You can comment out the code and break it down to see what might be causing it. Try it again and you can't figure it out, I'll give it a shot. Must be something stupid breaking. :)

**Comment by Soare-Robert-Daniel** [comment]
That is planned for today. I give it yesterday a little shot, but it was unsuccessful. I need to dig deeper.

**Comment by Soare-Robert-Daniel** [comment]
### The sad life of an `undefined` value

This error with React shows some interesting misuse of the `undefined` value in our components.

And all of it starts from here.

https://github.com/Codeinwp/gutenberg-blocks/blob/f3fb4b83b459bd759073d18f3ce32496879ef5e3/src/components/icon-picker-control/index.js#L184-L207

That conditional relays on the icon to be `undefined` to show the message `'Select icon'`.

But, in this update, the Icon can no longer be `undefined` because if it is `undefined`, the block will take the parent value. Because it takes the parent value, a mismatch between library and icon value is created, and so if it tries to render a Theme Isle Icon, it can not find it.

The solution was to stop trying to get the parent icon value so that the item icon to be `undefined` to trigger the conditional. Also, some additional checkers for `undefined` has been added to prevent displaying an `undefined` component.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel seems to be working fine now 👍

**Comment by HardeepAsrani** [comment]
Great. Thanks, @Soare-Robert-Daniel and @Soare-Robert-Daniel 😄

**Pull request merged**
