### PR TITLE
Add Masonry Variation

### LINKED ISSUE #725: Gallery Extension
An extension to change the default gallery extension into a masonry grid + a variant to make it easier for users to select the block.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Add Masonry variation to Gallery block. Fixes #725

A video showing how it works: https://www.loom.com/share/71246cad0964460da1a5b8c8ed317ff3

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel @irinelenache Can you see the video and test to make sure everything works?

**Comment by selul** [comment]
@HardeepAsrani can you confirm that the JS files responsible for the masonry are loaded only when the masonry type is used in the current page? We should not load the JS files on pages that don't need them

**Comment by irinelenache** [comment]
@HardeepAsrani For me it looks different in editor than frontend, and i get an error in console in front-end:

Editor: https://vertis.d.pr/By0TqE (looks the same with the Crop images option on/off)
Frontend with **Crop images on**: https://vertis.d.pr/vJEX9d
Frontend with **Crop images off**: https://vertis.d.pr/bdmkdj
Error in console: https://vertis.d.pr/WHTmlJ

Tested on Google Chrome, let me know if i missed anything, i'll do more testing after

**Comment by HardeepAsrani** [comment]
@selul Yup, only loaded if it’s a masonry.

**Comment by HardeepAsrani** [comment]
@irinelenache Thanks. Will check.

**Comment by Soare-Robert-Daniel** [comment]
### Backend - *crop on/off*
image

### Frontend - *crop off*
image

### Frontend - *crop on*
image

### Console error -> Frontend *crop on/off*
```javascript
jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
index.js:8 Uncaught TypeError: _wordpress_dom_ready__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
    at eval (index.js:8)
    at Module../src/frontend/masonry/index.js (masonry.js?ver=1.6.8:97)
    at __webpack_require__ (masonry.js?ver=1.6.8:20)
    at masonry.js?ver=1.6.8:84
    at masonry.js?ver=1.6.8:87
eval @ index.js:8
./src/frontend/masonry/index.js @ masonry.js?ver=1.6.8:97
__webpack_require__ @ masonry.js?ver=1.6.8:20
(anonymous) @ masonry.js?ver=1.6.8:84
(anonymous) @ masonry.js?ver=1.6.8:87
animate.js?ver=5.7.2:1 []

```

**Comment by HardeepAsrani** [comment]
I forgot to add wp-dom-ready as a dependencies. Can you add that for testing?

Regards,
Hardeep

**Comment by irinelenache** [comment]
@HardeepAsrani When i set the **Image size** to **Thumbnail**, the images added lose their quality, both with **Crop images on or off**
https://vertis.d.pr/mlnejd

**Comment by HardeepAsrani** [comment]
@irinelenache @Soare-Robert-Daniel 

Apologies, the wp-dom-ready was missing from frontend script so what you were testing was just plain gallery block. Can you test again and it should start looking a lot different. Also, crop on/off won't have any effect on it.

**Comment by HardeepAsrani** [comment]
Also I recommend using images of different sizes to test to give it better feel when testing.

**Comment by HardeepAsrani** [comment]
It should look more like this than boring grid: https://nimb.ws/4lkfHF

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, now they look exactly like in the front-end

**Comment by irinelenache** [comment]
@HardeepAsrani tested it again, overall it seems to work fine when image size is set to **Full size** 👍 found some things though:

- [ ] When size is set to Medium, with these settings https://vertis.d.pr/XND1vw , this is how it looks in frontend https://vertis.d.pr/u2822w

- [ ] The same image size looks different base on what setting was used before for image size
Large images when Medium was used before: https://vertis.d.pr/lzoB59
Large images when Full size was used before: https://vertis.d.pr/edRdvW

- [ ] There is a typo here, it should be **boring** https://vertis.d.pr/NE7aRP

**Comment by HardeepAsrani** [comment]
@irinelenache Can you check if it's all fixed now? Also try different themes so we know it works good everywhere. Thank you!

**Comment by HardeepAsrani** [comment]
@irinelenache Any update here?

**Comment by irinelenache** [comment]
@HardeepAsrani The fixes work fine, tested with other themes too 👍 
For tracking, would be ideal to have the issues in Themes prioritization so we don't forget about it

**Comment by HardeepAsrani** [comment]
@irinelenache Thanks for the review and feedback. I'll make sure to add it to the project from now on. If I don't, feel free to nudge me to say that I'm doing it wrong. :)

**Pull request merged**
