### PR TITLE
Make Advanced Heading line-height unitless

### LINKED ISSUE #712: Convert the Line-height from Advanced Heading to use Relative units
Advanced Heading block, lets users choose different font sizes on each device.
This is great, the challenge comes with the Advanced Heading **line-height**, which is one for all devices.

And this is not optimal, because for example on this page, the Desktop version uses 56px for **font-size** and for **line-heigh: 62px**
image

while on Mobile, the Heading is 38px with the same **line-height: 62px.**
image

My suggestion is to use a relative value for the line-height, relative to the Heading size.
I think unitless would be the best option, as the best practices [recommend](https://dev.to/lampewebdev/css-line-height-jjp) this approach.
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
Or we can try with percentages.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
@mghenciu This update will update the `line-height` range inspector picker to have values from 0 to 3 with a step of 0.1. Those are unitless so that it can respect the best practices from this reference: https://dev.to/lampewebdev/css-line-height-jjp

Build file is [here](https://slack-files.com/T0269KWNY-F02AP1VKP1D-e5274f74c5)

Closes #712

### CODE REVIEW

**Comment by mghenciu** [comment]
@Soare-Robert-Daniel , I tried to add the plugin file to a Jurassic instance, and I get a Warning and Fatal error when trying to activate it.
image
image

**Comment by mghenciu** [comment]
Awesome work @Soare-Robert-Daniel !
Here is a preview of the same design I was mentioning on the original issue, and it looks much better on mobile, when using relative units:
Screenshot 2021-08-17 at 14 23 13

I have just one question about this: how would this work on users sites that already use 'old' pixel line-heights for Advanced Headings? I am referring to the value conversion, make sure it doesn't go crazy with higher values.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, I've the same question. What will happen to the blocks which have already selected have some selected value. We need to make sure those don't just stop working or worse, becomes horrible.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]

**Comment by Soare-Robert-Daniel** [comment]
The old value are now normalized using a logarithmic function, the values will be from the [1, 2] interval.��

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Great but it will still not work properly in the editor for old headings. You need to make sure that old values are also taken care of in the editor. If you have a block with, let's say 150px, and you open the editor, you see a big line-height.

And we shouldn't use log here but just use px when it's above than 3. Some people might have chosen a particular value for their design.

**Comment by Soare-Robert-Daniel** [comment]
Now the old values greater than 3 are treated as `px`, new values will be unitless.﻿

**Comment by HardeepAsrani** [comment]
This should do the work. @irinelenache can you see if I’ve missed anything here or if it’s ready to be merged? 😀

**Comment by irinelenache** [comment]
@HardeepAsrani tested it and it seems to work fine 👍

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
