### PR TITLE
Release: 1.5.2

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Use WP File System in Template Import
- Fix CSS Regeneration
- Add TinyMCE in Map Marker
- Use ServerSideLoader in Author & Sharing Blocks
- Fix Posts Block for Gutenberg 8.0
- Display template name in Template Library
- Add AMP Support to Slider Block
- Remove Section Outline
- Add AMP Support to Google Maps Block
- Fix Horizontal/Vertical Alignment
- Add Template Preview in Template Library
- Fix issue with Color resetting in Button Group & Section
- Fix FA not loading on Index Pages
- Add two new templates
- Fix SVG issue in Slider & Section Block

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani here's what I've seen while testing this:

The **block previews** in WP 5.4.1

With the **Gutenberg plugin NOT installed**

- [ ] previewing the Slider block throws an error in the console


- [ ] preview for the Font Awesome Icons block. The icon is outside the container in the preview

 
- [ ] preview for the Plugin Card block. The layout is a bit off


- [ ] preview for the Advanced Heading block. The layout is a bit off


- [ ] Same for Google maps, sometimes the layout of the preview is ok. If you go over other blocks, and come back to it, the layout gets a bit off sometimes

With the **Gutenberg plugin installed**

- [ ] Google Maps preview sometimes throws an error, sometimes works well, if you go over other blocks and come back


- [ ] https://www.loom.com/share/03ebba900b4b4a788e401577743e234f - I got that error in most cases, even when just previewing the blocks. But one case I always got it, is after adding the Pricing block from inside the content, and after that going to the Add block button on the top left side, and try to preview Otter blocks like in the video

- [ ] Two things happening just in Neve, not in 2020, not sure if there's something related to Otter or Neve
https://prnt.sc/sixzba text color is grey, not white like in the screenshot
https://prnt.sc/siy3ki text color not black as in the editor

- [ ] Adding a third button using the Button Group block throws an error, with or without the Gutenberg plugin installed 
https://www.loom.com/share/882b27b691eb477eb5eee581fee423d1

**Comment by HardeepAsrani** [comment]
@rodica-andronache Should be fixed now. I've removed the preview as they are bit unstable on older releases. The styling is all haywire. Can you test again to make sure everything is alright now, also that you don't find any new ones? Thanks!

**Comment by rodica-andronache** [comment]
@HardeepAsrani 

- [ ] In 2020, the text color is different on frontend/editor for this template
download (3)
download (4)

- [ ] In Neve, this is still happening. The text color is different frontend/editor for this template
download (5)
download (6)

- [ ] and a thing that's happening with the current version as well, doesn't look to be specific to this PR, but thought to mention it.

If I add a slider block in a post, and after that, I go and activate Gutenberg, this error appears in the block. The same thing happens if I have Gutenberg activated while creating the post with the slider block, and after that, I go and deactivate Gutenberg and try to edit the post again.
download (7)

**Comment by HardeepAsrani** [comment]
@rodica-andronache Nice catch with the Slider issue. It's going to be hard to fix. It's not even our fault. Gutenberg just decided to change some things and now we have to somehow take care of the mess.

**Comment by HardeepAsrani** [comment]
@rodica-andronache can you test again? Here's a thing:

- Old sliders made on 5.4 will break on the new Gutenberg.
- If you open then once in 5.4 and save it, and then open it in Gutenberg, they will work fine.
- New sliders will work on 5.4 and Gutenberg.

Can you test all these things and confirm ^

The case should be same for Sliders & Sections with Dividier option.

**Comment by rodica-andronache** [comment]
@HardeepAsrani tested again and for the Slider I can confirm all three cases. For Sections, I couldn't replicate the issue in any case ( is there the same error as for the slider ?) How can I test that?

**Comment by HardeepAsrani** [comment]
@rodica-andronache Add a Section with 2 columns (or 3 or 4), and add a Divider from Style settings. After that activate Gutenberg, it will break the block. Try it with the current version of Gutenberg on wporg to understand the issue.

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks, I've checked that and it's working well too.

**Comment by HardeepAsrani** [comment]
All good to release this? :D @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani let me check the first two things related to the templates too. I wasn't sure that was finished

**Comment by rodica-andronache** [comment]
@HardeepAsrani 
In Neve, this is still happening. The text color is different frontend/editor for this template
download (5)
download (6)

**Comment by HardeepAsrani** [comment]
@rodica-andronache I'm gonna skip this one for now. Will fix it in upcoming, as it's really a non-issue for the most part.

Thanks for the testing and specially finding that Slider issue!

**Pull request merged**
