### PR TITLE
Return of the Hook Id

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
The functions that generated the block id has been cleaned up and moved to a separate file. 

From copy pasting this code in every block:
```javascript
	useEffect( () => {

		initBlock();
	}, []);

	const initBlock = () => {
		const blockIDs = window.themeisleGutenberg.blockIDs ? window.themeisleGutenberg.blockIDs : [];

		if ( attributes.id === undefined ) {
			let attrs;
			const instanceId = `wp-block-themeisle-blocks-advanced-columns-${ clientId.substr( 0, 8 ) }`;

			const globalDefaults = window.themeisleGutenberg.globalDefaults ? window.themeisleGutenberg.globalDefaults : undefined;

			if ( undefined !== globalDefaults ) {
				if ( ! isEqual( defaults[ name ], window.themeisleGutenberg.globalDefaults[ name ]) ) {
					attrs = { ...window.themeisleGutenberg.globalDefaults[ name ] };

					Object.keys( attrs ).map( i => {
						if ( attributes[i] !== attrs[i] && ( undefined !== defaultAttributes[i].default && attributes[i] !== defaultAttributes[i].default ) ) {
							return delete attrs[i];
						}
					});
				}
			}

			setAttributes({
				...attrs,
				id: instanceId
			});

			IDs.push( instanceId );
			blockIDs.push( instanceId );
		} else if ( IDs.includes( attributes.id ) ) {
			const instanceId = `wp-block-themeisle-blocks-advanced-columns-${ clientId.substr( 0, 8 ) }`;
			setAttributes({ id: instanceId });
			IDs.push( instanceId );
			blockIDs.push( instanceId );
		} else {
			IDs.push( attributes.id );
			blockIDs.push( attributes.id );
		}

		window.themeisleGutenberg.blockIDs = [ ...blockIDs ];
	};
```

Now we have this one:
```javascript
	useEffect( () => {
		const unsubscribe = addBlockId({
			attributes,
			setAttributes,
			clientId,
			name,
			idPrefix: 'wp-block-themeisle-blocks-advanced-columns-',
			defaultAttributes
		});
		return () => unsubscribe();
	}, []);
```

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @Soare-Robert-Daniel,

It looks great for the most part. Use the Template Library and import the first Neve template twice and both will have the same IDs. That shouldn't be allowed to happen.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani made some tests with WP 5.5, everything looks fine; the new system does not try to override the existing ids on the blocks.

I was testing block created in 5.7.2 then downgraded to 5.5. And vice versa with blocks created in 5.5 with the old mechanism and tested in 5.7.2 with the new one

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, we need some tedious testing for this feature. In this PR, we change how an internal variable is constructed, and this interval variable is a critical part of the block. If you insert a `Slider` or a `Progress Bar`, and to Code Editor Mode you will that they an `id` property (like this `"id":"wp-block-themeisle-blocks-circle-counter-912c2ad3"`). **We need to ensure that this `id` does not change for the already present blocks on the page**. If it does, it might break a lot of things (usually CSS solution based on the `id` written by the user), and the process might be irreversible.

For this update, we need to test those conditions:

- Current Blocks will not change their ID
- If you copy a block and paste, it must not have the same ID as the source
- If you duplicate a block, it must not have the same ID as the source

If one condition is not respected, please post a detailed explanation or a video with the procedure.

Also, while testing, I recommend using a text editor. Because for checking, you will need to copy the page information and compare it. Something like this:

If you have the fallowing code: `<!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-ea55ec10","columnWidth":"50"} -->`. When you refresh the page the `id` must be the same.

Also, recommend testing this on the some older WP version like 5.5.

So, you will need to make a page with almost all the Otter blocks. Save it. Copy the page, switch to the new system, and check if everything is alright. Then you can play with them to copy and duplicate it and check again if the ID is unique. On the new system, in the console, it will display the current id on the page; you can use it for verification.

**Comment by HardeepAsrani** [comment]
I'm testing it right now but for one, can you make the hook smaller? Instead of:

```
const unsubscribe = addBlockId({
	attributes,
	setAttributes,
	clientId,
	name,
	idPrefix: 'wp-block-themeisle-blocks-icon-list-',
	defaultAttributes
});
```

You should be able to generate the idPrefix from the name attribute as all of them follow the same pattern. And can also just get the defaultAttributes within the hook itself instead of passing it from the hook. Makes sense? @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
In fact... you can remove all the parameters and just pass clientId to do the rest. You can get the block from within the hook and use attributes, setAttributes & name. That will make things really easier. :)

**Comment by HardeepAsrani** [comment]
Also, remove the `initBlock` function from the Circle Counter block.

**Comment by HardeepAsrani** [comment]
Rest seems fine to me. Can you test it too @irinelenache? Thank you!

**Comment by Soare-Robert-Daniel** [comment]
> In fact... you can remove all the parameters and just pass clientId to do the rest. You can get the block from within the hook and use attributes, setAttributes & name. That will make things really easier. :)

There is no hook, `addBlockId` is just a simple function. The first version was designed as a hook. It was a bad idea, full of bugs. So I will not put any hooks inside. Auto-generating `idPrefix` is a nice idea.

A nice solution for a straightforward and bug-free method is to enhance the block. 

And so, a nice method was born.

```javascript 
/**
 * Ehance the block by adding the id generating functions
 * @param {*} Block An Otter Block
 * @param {Object} defaultAttributes The default attributes of the block.
 * @param {(string|undefined)} idPrefix (Optional) The prefix used for generating the block id
 * @returns {React.FunctionComponent} An enhanced component
 */
export const OtterBlock = ( Block, defaultAttributes, idPrefix = undefined ) => ( props ) => {
	const { attributes, setAttributes, clientId, name } = props;
	useEffect( () => {
		const unsubscribe = addBlockId({
			idPrefix,
			attributes,
			setAttributes,
			clientId,
			name,
			defaultAttributes
		});
		return () => unsubscribe();
	}, []);
	return <Block {...props}/>;
};
```

With the usage:

```javascript
import './style.scss';
import './editor.scss';
import attributes from './attributes.js';
import edit from './edit.js';
import save from './save.js';
import transforms from './transforms.js';
import { OtterBlock } from '../../helpers/enhancement';

registerBlockType( 'themeisle-blocks/circle-counter', {
	title: __( 'Circle Counter' ),
	description: __( 'Show your progress with a beautiful Circle Counter block.' ),
	icon,
	category: 'themeisle-blocks',
	keywords: [
		'progress',
		'circle',
		'counter'
	],
	attributes,
	transforms,
	edit: OtterBlock( edit, attributes ),
	save
});
```

With this, `addBlockId` remains just a simple function. And the `OtterBlock` is just a reusable component ( a middleware ). And by using it on the `index.js` we have also easy access to `defaultAttributes` which is just `attributes`.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel I tested these conditions

> Current Blocks will not change their ID
If you copy a block and paste, it must not have the same ID as the source
If you duplicate a block, it must not have the same ID as the source

and they seem to work fine 👍 

Found a problem, when i have some blocks created and update the plugin to this version, i get an error when i try to open the page in front-end https://vertis.d.pr/52bbli

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, that other issue doesn't have anything to do with this PR but thanks for finding it out. I'll fix it.

**Comment by Soare-Robert-Daniel** [comment]
The new form is:

```javascript
useEffect( () => {
    const unsubscribe = blockInit( clientId, defaultAttributes );
    return () => unsubscribe();
}, []);
```

@irinelenache , @HardeepAsrani for this simplification some extra mechanism has been added. Can you re-test to check if everything is ok?

**Comment by HardeepAsrani** [comment]
Still the old issue: https://www.loom.com/share/a3297f9c4cd449b080b39c42f65222e2 - add a custom ID and duplicate it.

**Comment by HardeepAsrani** [comment]
^ @Soare-Robert-Daniel

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, this issue happens even on the normal one. Since the new mechanism mimics the current one, this problem was also inherited.

The reason for this is simple: there is no detection for the dynamic change of the `id`.
```javascript
	useEffect( () => {
		initBlock();
	}, [ ]);
```

As you can see, the magic is happening only in the creation phase. If I change the `id`, the new value will not be saved in the `IDs`; thus, it will be the same id when I duplicate or copy. This problem solves itself after saving and page refresh. But if you write some code when the same id is still there, it might cause some problems.

To fix this, you need to do the following addition:
```javascript
	useEffect( () => {
		initBlock();
	}, [ attributes.id ]);
```

The big question is: Was it a problem until now? This mechanism probably more than [1-year-old since implementation](https://github.com/Soare-Robert-Daniel/gutenberg-blocks/commit/eb35ecee0b0fe2f97e21b345fa2223715a8bbe66). Is there some part of the code that might work only with the old mechanism which we might not know or expect to be like that?

I will push the fix and check if something unexpected might happens.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel tested again and it looks like it's working fine for me, the custom ids aren't duplicated now

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's old code so I don't remember everything properly but I suppose we were doing the detection here https://github.com/Codeinwp/gutenberg-blocks/blob/master/src/components/html-anchor-control/index.js#L71-L75 to update the global variable with new IDs.

**Comment by HardeepAsrani** [comment]
I suppose everything works properly now @irinelenache? If yes then can you remove the console logs @Soare-Robert-Daniel  from the code?

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel It's old code so I don't remember everything properly but I suppose we were doing the detection here https://github.com/Codeinwp/gutenberg-blocks/blob/master/src/components/html-anchor-control/index.js#L71-L75 to update the global variable with new IDs.

This only happens for the global scope, and the mechanism is only using the local scope. But since the id is duplicated, this doesn't do too much.

**Comment by HardeepAsrani** [comment]
Good work @Soare-Robert-Daniel. Thanks @irinelenache for the testing!

**Pull request merged**
