### PR TITLE
Version 1.2.4

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Fix Internet Explorer incompatibility
- Add option to choose Marker icon for Google Map
- Open marker tab when clicking on Marker on Map

### CODE REVIEW

**Comment by radu-themeisle** [comment]
**Map**
- The longitude and latitude update as you move the map. Shouldn't the [location](http://prntscr.com/ok736d) do the same? 🤷‍♂️
- Updated, viewed the page and came back to [this](http://prntscr.com/ok74k3) 😲 It also asks me to update the post but I didn't make any changes. No errors in the console so I thought maybe there's an issue with Jurassic but I tried with a new page and got the same result.
Tested also with a post and I don't get the "squeezed" block but it still shows like I edited something and [asks me to update](http://prntscr.com/ok76m4) (still no error in the console).
_Update_: so I figured out what generates the "squeeze", it's because the block ends up in a section within a section within a section. Here's a [video](https://www.loom.com/share/eea9916278d746b8bf2e742e583cd4f3) to make it easy to understand what's happening. If I remove the section block when I create a new page and add the Map block then there's no issue, but I still get that annoying "Update" without having changed anything.
- Just and idea (maybe in a future release): can you make it so that if you add a marker from the sidebar the map focuses on the location?
e.g. I added a marker with "Berlin" and the map stayed on Barcelona instead of jumping to Berlin. I believe it would aid users as it will allow them to focus fast on their location of interest.

**Map Marker**
- When adding a marker if you try to select the title after writing it it [closes the window](https://www.loom.com/share/9bb7025a1a7e452da619bdc77fa61e1c). It happens also if you use the "add marker" menu from the sidebar.
- arrows keys not [going through marker color options](https://www.loom.com/share/97425488ccf54cb0b9de9334b90a73db) instead it scrolls the page. I was using my keyboard to go through the inputs (you'll probably say it's a G issue 😄).
- "Add options to choose Marker icon": I thought I can change the icon, I figured it's actually about changing the color so maybe you can change so it says "Marker icon color" to be clear for everybody.

**IE 11**
Everything looks ok, I got some issues but I don't think there's anything we can do about it:
- Went to edit the page that already has the Map block and got [this](http://prntscr.com/ok7byw). Went back and edited again and it was ok, so it's IE's fault.
- Adding Map Marker from the block doesn't work in one case but works in the other. First one is added from the menu on top of the page title, the second was added directly from the body of the editor from the suggested. I believe it's an [IE issue](https://www.loom.com/share/ec56fa5a43f047d5818355b0624e2aa5).

**Comment by HardeepAsrani** [comment]
> The longitude and latitude update as you move the map. Shouldn't the location do the same? 

No, you can also move the map to select the location.

> Updated, viewed the page and came back to this 😲 It also asks me to update the post but I didn't make any changes. No errors in the console so I thought maybe there's an issue with Jurassic but I tried with a new page and got the same result.
> Tested also with a post and I don't get the "squeezed" block but it still shows like I edited something and asks me to update (still no error in the console).

Seems to be an issue with Hestia/Neve's Gutenberg integration in the backend. It's causing this. Try it with some other theme and it should be fine.

> Just and idea (maybe in a future release): can you make it so that if you add a marker from the sidebar the map focuses on the location?

That's in my list but trying to figure out a way to do it with user consent.

> arrows keys not going through marker color options instead it scrolls the page. I was using my keyboard to go through the inputs (you'll probably say it's a G issue 😄).

Well, that's a G issue. G being Google Chrome. It's a normal HTML input and noting else, and in Google Chrome you need to press `space` to see the options. 

> "Add options to choose Marker icon": I thought I can change the icon, I figured it's actually about changing the color so maybe you can change so it says "Marker icon color" to be clear for everybody.

Alright, thanks!

> Went to edit the page that already has the Map block and got this. Went back and edited again and it was ok, so it's IE's fault.

Can you try again with Twenty Nineteen and see how it works? Also try once without Section block. And make a video of it with console open. 

> Adding Map Marker from the block doesn't work in one case but works in the other. First one is added from the menu on top of the page title, the second was added directly from the body of the editor from the suggested. I believe it's an IE issue.

Works fine on IE11 on BrowerStack for me. With you?

**Comment by radu-themeisle** [comment]
Went back to test based on your reply an indeed it's also an issue coming from the theme so I switched to twentyninteen. Chrome seems ok, IE presented some issues so [here's a video](https://www.loom.com/share/a1f1827f97ee47728993ee81f6d93065).

**Comment by HardeepAsrani** [comment]
@radu-themeisle In your video, why was the block broken in the beginning on IE?

**Comment by radu-themeisle** [comment]
@HardeepAsrani For apparently no reason. It was an existing post with the map block which I opened in IE

**Pull request merged**
