### PR TITLE
Add Tabs Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Implemented Features

- Switch tabs mechanism for desktop and mobile
- Base design inspired from https://demosites.io/music-band/music-band-single-album/
- Add Tabs button for desktop
- Select the first tab on initialization
- Inspector
    - Sortable Tabs
    - Edit Button to go the tab's inspector & Back Button
    - Delete Button
    - Add Tab Button
- Save functions
- Frontend script
- Add Inspector for styling the block
- Save functions
- PHP for generating dynamic CSS
- Block controls

### Known bugs
- `InnerBlocks` is not saving the content

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Looks. Make sure when the editor reloads, the first tab is always open. Also, can you remove the tabs from the Inspector Sidebar? People can just take care of it from the editor. The delete button can be over the tab title when it's selected. Similarly how one can move it.

**Comment by HardeepAsrani** [comment]
Let me know when the changes we discussed in the meeting are finished. Thanks!

**Comment by HardeepAsrani** [comment]
Icons look weird on Firefox

Screenshot 2021-06-15 at 1 29 44 AM

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  All done. If you still do not like the Add Button icon size, you can change it here https://github.com/Soare-Robert-Daniel/gutenberg-blocks/blob/275a7cbab5b8e9d8ebcf5fb92eabb926d777a51f/src/blocks/tabs/group/editor.scss#L19-L22

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, can you test if this block works correctly?

If you have an error for PHP in which the class is not defined, run this command `composer dumpautoload -o` in the `otter-blocks` folder.

**Comment by HardeepAsrani** [comment]
It's almost there here's a video review and points noted also in the text below: https://www.loom.com/share/340319a3b3d04f91a1e25ed7c3a8e4a9

- Move the "+" button to center + only show when the block (or inner blocks) are selected.
- People should be able to edit the title easily.
- Default title should be empty, use a placeholder text instead of actual text.
- Make moving component more as we use in Posts Block + background in that tab.
- Use Horizontal orientation in tabs' Innerblock.
- Use the color contrast component to make sure contrast is good.
- Use cursor style of tab title in front to be a pointer.

The rest looks pretty neat. @Soare-Robert-Daniel

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel

- Shouldn't the text here https://vertis.d.pr/kVCOzM be **Selected tab title color** ?

- The Maps block doesn't look ok in front-end when it's added in a Tab https://vertis.d.pr/S78dag

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the requested features have been implemented. 
Regarding the Maps Block, I do not think that I can do much about it. Leaflet does not always behave nice.

**Comment by HardeepAsrani** [comment]
Hey @Soare-Robert-Daniel,

Can you take a final look to see if everything works? Here are the changes that I made:

- Redid frontend code.
- Removed Headers attributes from Parent Block.
- Removed ID from child block.
- Many minor improvements or edits.

Let me know how it goes!

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I found some issues:
 - [ ] The block gets an error when you insert a `tab item`. If you save and refresh, it will work, but if you try o add another `tab item` by inserting another `tabs block` or press the `+` on the block inserter previously. The issue is: `Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`. This is triggered by the `InnerBlock` of the `tab item`.
 - [ ] In Frontend, if you have nested tabs, the parent will deactivate all its children. Check [1], [2]. You can try to fix this by removing the children from the array. Check my initial implementation of [this commit](https://github.com/Codeinwp/gutenberg-blocks/pull/683/commits/6aeb3300f059392d4dc16f8194eb1a6a6f9b2376)

Reference [1]: Initial view
image

Reference [2]: After switching and returning
image

**Comment by HardeepAsrani** [comment]
> In Frontend, if you have nested tabs, the parent will deactivate all its children. Check [1], [2]. You can try to fix this by removing the children from the array. Check my initial implementation of this commit

@Soare-Robert-Daniel This can be fixed by replacing this:

> tab.querySelectorAll( '.wp-block-themeisle-blocks-tabs__content > .wp-block-themeisle-blocks-tabs-item' )

with:

> tab.querySelectorAll( ':scope > .wp-block-themeisle-blocks-tabs__content > .wp-block-themeisle-blocks-tabs-item' )

Don't need to make write complex logic for this.

**Comment by HardeepAsrani** [comment]
I'm merging this and we can have a final QA by @irinelenache once it's all ready to ship.

**Pull request merged**
