### PR TITLE
Block Conditions

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Adding conditions to control the visibility of the block.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @irinelenache @Soare-Robert-Daniel ,

When you get the time please review this too. Here's a video explaining how it works: https://www.loom.com/share/95521b58c096465e9d64206f54c37d41

**Comment by irinelenache** [comment]
@HardeepAsrani I don't exactly understand how the time conditions work. On the wp instance i set my local time but i think the block conditions still use the universal time.
The editor settings: https://vertis.d.pr/ynGXJb
Frontend: https://vertis.d.pr/YkQ5Wk

**Comment by HardeepAsrani** [comment]
@irinelenache Can you let me know which timezone you were using so I could try to reproduce it on my end? Thanks.

Apart from timezone sucking, did you find any other issues?

**Comment by irinelenache** [comment]
@HardeepAsrani I selected Romania timezone
Didn't find anything for now, will have to test it a bit more and will let you know 🙏

**Comment by HardeepAsrani** [comment]
@irinelenache Should be fixed. Can you take a look and let me know if it works fine now?

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and it works fine overall, good job 🚀 

I have a question regarding the Post meta conditions:
If i set it like this https://vertis.d.pr/EoNtWM the block isn't visible, but if i change the **If equals** operator to **If contains** it works fine. For the if equals condition should i enter the meta value in a different way?

Also, something small that i didn't understand: 
If i enter 2 conditions (https://vertis.d.pr/Nl9nVD), is it normal to have one control for each to set the block as Visible/Hidden?

**Comment by HardeepAsrani** [comment]
@irinelenache if_equals condition should work now. Can you check and confirm if it's ready to be merged? It wasn't working because... I forgot to add the code. 😛

**Comment by irinelenache** [comment]
@HardeepAsrani tested again and everything works fine 👍

**Pull request merged**
