### PR TITLE
Add code formatter

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
@HardeepAsrani I added prettier (and the command line) as code formatter, the EsLint file was updated to work with prettier. Also added new plugin for EsLint to check the use of hooks (is was pretty useful in LogoMaker) - if check the file, the EsLint should emit a warn regarding the use of hooks.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
It looks good but can you change some rules to make it more like before? Spaces between brackets & parenthesis, line breaks in array & object. It changes too much of the code to make it look uglier.

**Comment by Soare-Robert-Daniel** [comment]
It has very few options. As the [docs](https://prettier.io/docs/en/index.html) says:  "Prettier is an opinionated code formatter". It is imposing a coding style. Unfortunately, the features that you requested are not available.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Those options are coming from their ESLint presets, not from Prettier settings, so you will have to add it in ESLint config.

**Comment by Soare-Robert-Daniel** [comment]
We should let EsLint for checking for undefined variables, unused var, etc. and Prettier for formatting. Making EsLint to format code will complicate things.

On Logo Maker, the combination of Typescript + EsLint + Prettier it's given from heaven. Everything just works.

The personal pain with the current settings is that EsLint will make all my editor red and stress me out because i don't put that additional space on brackets, parenthesis, etc.

In my opinion, EsLint is for pointing potential bugs and not where I need to put a space, so that the code will look good.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel But that's really not the case. Right now if I write the code my way then eslint will show red. So it has nothing to do with Prettier's autoformat. Those things that I said aren't coming from Prettier but from Prettier's ESLint presets. For making that your editor doesn't go right, you can setup to run ESLint's auto fix each time you save the file.

**Comment by Soare-Robert-Daniel** [comment]
The main thing, I can't have the EsLint and Prettier run simultaneously on Vs Code when I press `CTRL + S`.

I am willing to drop EsLint, since it is not a true formatter.

**Comment by HardeepAsrani** [comment]
Is it still fine or will be drop this in favor of the new PR you made about TypeScript?

**Comment by Soare-Robert-Daniel** [comment]
After testing on the `bleeding-edge` branch, Prettier with our current EsLint config does not look very good. The semi-formating will be done with the new EsLint config on the `bleeding-edge` branch for the moment.

**Pull request closed without merging**
