### PR TITLE
Version 1.6.0

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- New Icon List Block.
- Allow editing text in Progress Bar Block.
- Reuse Gradient Control from Core.
- Fix Font Awesome loading when the non-Icon button is being used.
- Improve Server-Side CSS Method

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @rodica-andronache!

Can you test this before the release? Major things are mentioned in the PR details, just a few notes from me:

- Make sure Font Awesome doesn't load unless it's being used.
- New Icon List block is added so make sure it's all good.
- Replace Gradient Control in Section with one from Core, so make sure Section/Section Column doesn't break.

Let me know if you have time to test it. Thanks!

**Comment by rodica-andronache** [comment]
@HardeepAsrani 
- [ ] when editing the text inside the progress bar, you can add various text formatting, which looks ok in the editor, but not the same on the frontend
download (2)
download (4)

- [ ] there's a small misalignment in the gradient control ( not sure if it's from the core ). I've tested on Chrome
download (5)

- [ ] for both the `Icon List` and `Icon` blocks, when I chose `ThemeIsle Icons`, or don't select an icon at all, font awesome is still loading ( from what I've understood, that shouldn't happen in those cases ).
download (6)

@irinelenache you can give it a try too, maybe you spot other issues

**Comment by irinelenache** [comment]
- [ ] If i set a bigger `Progress bar` (bigger height and a longer text) https://prnt.sc/w7tr2z , on mobile it doesn't get smaller and it looks like this https://prnt.sc/w7trl1

> when editing the text inside the progress bar, you can add various text formatting, which looks ok in the editor, but not the same on the frontend

- [ ] Same happens with the `Circle counter`
- [ ] If `Background type` is set to `Gradient` and no gradient is selected, the background is white in editor but has a default gradient in front-end. https://prnt.sc/w7udht https://prnt.sc/w7udnp

**Comment by HardeepAsrani** [comment]
`If Background type is set to Gradient and no gradient is selected, the background is white in the editor but has a default gradient in front-end. https://prnt.sc/w7udht https://prnt.sc/w7udnp`

@irinelenache Yea, normally if you don't want a gradient then don't use the tab. If the value is empty, it uses the default. Another thing that can be done is to make the "Clear" button change to the default gradient rather than empty. What do you think?

**Comment by HardeepAsrani** [comment]
> for both the Icon List and Icon blocks, when I chose ThemeIsle Icons, or don't select an icon at all, font awesome is still loading ( from what I've understood, that shouldn't happen in those cases ).

The Parent block, Icon List, must've "Font Awesome" selected as te default library. Is that the case?

**Comment by HardeepAsrani** [comment]
cc @rodica-andronache - last message is for you, forgot to tag. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani you're right. I wasn't aware that I have to change the library for the parent block as well. This way, everything works well. Even though I find it a bit confusing :)

**Comment by irinelenache** [comment]
@HardeepAsrani 

> Yea, normally if you don't want a gradient then don't use the tab. If the value is empty, it uses the default. Another thing that can be done is to make the "Clear" button change to the default gradient rather than empty. What do you think?

Even if the clear button gets the gradient to empty or the default color, i think the important thing is that it looks the same in editor and front-end, so there are no confusions

**Comment by HardeepAsrani** [comment]
Okay all fixed. We can release once you review this PR: https://github.com/Codeinwp/gutenberg-blocks/pull/554 - @irinelenache

**Pull request merged**
