### PR TITLE
Docs Revolution

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Add Mkdocs Material as the engine for rendering docs. 

Docker images for running and building: https://hub.docker.com/r/squidfunk/mkdocs-material/
Main site: https://squidfunk.github.io/mkdocs-material/

Images:

image

image

image

image

### CODE REVIEW

**Comment by selul** [comment]
@Soare-Robert-Daniel keeping in the VCS the whole docs engine, i.e `/site` folder is bad IMHO not sure if this is due to how the docs engine you chose is working or not, however, a more lightweight version would be better. Github pages are good too.

**Comment by selul** [comment]
and also why here and not on the otter repo? since it incorporate multiple packages, including this

**Comment by HardeepAsrani** [comment]
Yea, you can move it to Otter. Also, we can use GitHub pages or even the GitHub Wiki, no need to maintain a separate engine.

**Comment by Soare-Robert-Daniel** [comment]
The `/site` folders are generated by the engine as default. I do not like GitHub Wiki because it is too simple and doesn't have a decent search option. To enable GitHub pages, it will a little `bash` script to extract the `/site` content since Github search only in `/` and `/docs` for the `index.html`

Also, I think is better to be in his own repository, something like `otter-docs`.

**Comment by HardeepAsrani** [comment]
It's mostly for our internal use and even that it's barely used so it's better to not spend too much time on it but just add a simple wiki, or just maintain readme files. Also, one reason for markdown files was so that people can just look it inside from their editor as it's useful while coding.

**Comment by Soare-Robert-Daniel** [comment]
Now we use it for this project. But tomorrow it could be more. Also, the point of working in the editor is not that good. For me, I want the documentation to be on a separate monitor and the editor on the other. Switch tabs in the editor or taking space for a split view is not a good experience.

The documentation on most of our projects is almost non-existent. When I started it was pretty hard to get used to how the project works since there were no indications. We could use the experience from this to transfers to other projects. People might look at it and see if it's useful.

**Comment by HardeepAsrani** [comment]
Most of the docs are on notion.io, which reminds me, should we move this there too @selul?

**Comment by selul** [comment]
I like the idea of self repository more + Github pages. I agree with having for products but what I would like is this to be easy to maintain and scale to different products.

**Pull request closed without merging**
