### PR TITLE
Countdown Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Editor

- [x] Display time basic structure
- [x] Display time for save function

### Inspector

- [x] Change deadline
- [x] Change colors
- [x] Change size
- [x] Change font-size
- [x] Change spacing
- [x] Change border
- [x] Change time picker format: 12H or 24H
- [x] Select time component

### Frontend Script
- [x] Load script with PHP
- [x] Run countdown with JS
- [x] Generate CSS style with PHP

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
- Border Radius doesn't work.
- Separator isn't in the middle.
- Calendar in the editor looks weird, put it inside a Placeholder component to make it look better.
- Which timezone is used in the countdown?

**Comment by HardeepAsrani** [comment]
@irinelenache Can you also take a look?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Also, how does 12 hour format work in a Countdown? I don't understand that at all. It isn't making a lot of sense to me at least.

**Comment by HardeepAsrani** [comment]
@mghenciu Can you also take a look to see if anything is needed for the demo sites?

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel Also, how does 12 hour format work in a Countdown? I don't understand that at all. It isn't making a lot of sense to me at least.

The 12-hour format is just to set the time picker to have PM and AM buttons. Some people prefer 24h (like Europe), some 12h (like USA).

**Comment by mghenciu** [comment]
> @mghenciu Can you also take a look to see if anything is needed for the demo sites?

As always, I can't build the Plugin 😅 , so a Build file would help.
I am also thinking about the time format, but I'll test and see.

Essentially the time has the same value, no matter what type of time format you use. The only difference may be in the UI, how the time is display where you select it.

**Comment by mghenciu** [comment]
Overall, nice start @Soare-Robert-Daniel ! 💪 

Things that I noticed so far: (some may be ideas of improvement, some are just first impressions)

- [ ] the preview in the Right panel it's a good idea, but I would stick to the defaults views, to only give users the idea how that Style looks (not Reactive as it is now). Why? because when a user starts to customize the block, the Style preview can get (visually) broken. One example is, if the user uses White color for Values, then nothing will be visible in the Style preview:
Screenshot 2021-07-27 at 13 44 28
or if you start adjusting the font size & spacing -> the content in preview gest outside the box.
image

- [ ] I think by default, the separator should be vertically aligned with the Time Values, not the whole Column. So it should be something like this:
image
This is how it looks now:
Screenshot 2021-07-27 at 14 08 45

- [ ] another option for the separator, could be having 2 Styles for it, one with the colon sign, and one with a border/vertical line between each component. Something like [here](https://dribbble.com/shots/5245225-Daily-UI-014-Countdown-Timer).

- [ ] the right scroll-bar/sidebar moves on each second, and that's visible + it doesn't look very profesional having it moving like that >> https://www.loom.com/share/cf842f1134e9430cafb42f482213e13e 

For the 12 hours format, I only can image this usecase: let's say a users is more familiar with the 12 hour format, then it would use that one. Other than this, I am not sure what else it can bring to the table.

Here's [the sandbox ](https://willing-tapir.jurassic.ninja/countdown/)with a few examples I've tested on.

**Comment by HardeepAsrani** [comment]
> For the 12 hours format, I only can image this usecase: let's say a users is more familiar with the 12 hour format, then it would use that one. Other than this, I am not sure what else it can bring to the table.

@mghenciu @Soare-Robert-Daniel The issue here is that 12 hour format is being saved to block's attributes which makes no sense. It can be just a state and stored into browser storage that way people can pick the format which us having to save it to the attributes as we don't really need to use it in the frontend.

**Comment by HardeepAsrani** [comment]
>  the preview in the Right panel it's a good idea, but I would stick to the defaults views, to only give users the idea how that Style looks (not Reactive as it is now). Why? because when a user starts to customize the block, the Style preview can get (visually) broken. One example is, if the user uses White color for Values, then nothing will be visible in the Style preview:

Can't do much about it. That's just how styles work. :)

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel nice work 🚀  tested it a bit and found some issues:

- [ ] If the countdown looks like this https://vertis.d.pr/8gvzYi and i disable days from settings, it becomes like this in editor https://vertis.d.pr/KeMRgA (i would expect it to convert the days into hours and add them to the hours countdown). Also, in front-end it throws some errors and the countdown doesn't work https://vertis.d.pr/9jpkQg

- [ ] If i have a style like **asymetric / pocket** selected and change the value for **border radius**, the style is not applying anymore in frontend and i have to delete and create again the block in order to have the desired style
editor: https://vertis.d.pr/7gasA2
frontend: https://vertis.d.pr/CYopbJ

- [ ] If i have **separators** added and change the **Box width**, the separator inherits the width too and the countdown becomes bigger than it should
editor: https://vertis.d.pr/vh3h0f
frontend: https://vertis.d.pr/w0F0CH

- [ ] The separator is inheriting the background color, i don't know if this is expected https://vertis.d.pr/No47WT 

- [ ] On mobile, the block gets out of the screen https://vertis.d.pr/6BDP7n

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  If the countdown looks like this https://vertis.d.pr/8gvzYi and i disable days from settings, it becomes like this in editor https://vertis.d.pr/KeMRgA (i would expect it to convert the days into hours and add them to the hours countdown). Also, in front-end it throws some errors and the countdown doesn't work https://vertis.d.pr/9jpkQg

An interesting remark, I didn't think about it. I do not know if it is usual to have a countdown that shows 300 min instead of 5 hours. @HardeepAsrani @mghenciu what do you think?

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  the right scroll-bar/sidebar moves on each second, and that's visible + it doesn't look very profesional having it moving like that >> https://www.loom.com/share/cf842f1134e9430cafb42f482213e13e

I do not have this problem with Chrome on Windows 10. Are you using a Mac with Safari or Chrome?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani @irinelenache can you re-test the block?

**Comment by mghenciu** [comment]
> > * [ ]   the right scroll-bar/sidebar moves on each second, and that's visible + it doesn't look very profesional having it moving like that >> https://www.loom.com/share/cf842f1134e9430cafb42f482213e13e
> 
> I do not have this problem with Chrome on Windows 10. Are you using a Mac with Safari or Chrome?

Yes, it happens in Chrome, macOS. 
I tried in Safari & Vivaldi, but there it works as expected. So I guess it's something device/OS based.

Regarding the new Modern Style, @Soare-Robert-Daniel , looks good. The only things I noticed is the fact that the Box Spacing is not working, when a user selects the **Modern Style** (not sure if this in intended).

And if possible, when a user enables the Modern Style, to uncheck Display Separators. Because by design you would use just one of them (Line or colon sign). And not like this:
image





> > * [ ]   If the countdown looks like this https://vertis.d.pr/8gvzYi and i disable days from settings, it becomes like this in editor https://vertis.d.pr/KeMRgA (i would expect it to convert the days into hours and add them to the hours countdown). Also, in front-end it throws some errors and the countdown doesn't work https://vertis.d.pr/9jpkQg
> 
> An interesting remark, I didn't think about it. I do not know if it is usual to have a countdown that shows 300 min instead of 5 hours. @HardeepAsrani @mghenciu what do you think?

From a quick research it look like other Blocks just hide the desired piece of information (for example Day), without converting the time to the enabled content. So it should be fine how it works now, show-hide.


Another thing I noticed while researching, is the option to Edit the labels. What this required? should be?
Or how would this work with translation plugins?
**Use case:** I have a site in Russian, how I would make the Labels to also be in Russian.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] Now when i activate separators, the block isn't visible at all in frontend https://vertis.d.pr/pGvt2j
- [ ] If i change the style to custom and change the border radius, i can't switch back to other styles because the border radius still applies https://vertis.d.pr/KtpcAe
- [ ] On mobile, the block still gets out of the screen
- [ ] When the modern style is selected, the Box spacing isn't applied in editor https://vertis.d.pr/PABRG6

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache I hope that the dimensions are enough for the screen. 
@mghenciu The separators have been removed from the Moder style since they do not make sense for this case. Also, we will use otter translation for the base words. They are basic words, I do not think it will be a problem ( the ideal case).

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, the Chrome glitch is bizarre. Possible to be a temporary bug. In Edge is present, but Vivaldi is not, and they are both Chrome-based.

**Comment by irinelenache** [comment]
> If i have separators added and change the Box width, the separator inherits the width too and the countdown becomes bigger than it should
> editor: https://vertis.d.pr/vh3h0f
> frontend: https://vertis.d.pr/w0F0CH

This still happens, only on frontend

> The separator is inheriting the background color, i don't know if this is expected https://vertis.d.pr/No47WT

This one still happens, again only on frontend
editor: https://vertis.d.pr/i73rcX
frontend: https://vertis.d.pr/mxnO9e

- [ ] With modern style selected, shouldn't the separators be centered between every two numbers? https://vertis.d.pr/GETD1X
- [ ] With modern style selected, i can change the separators width only by changing the border width, i don't know if this is expected
- [ ] With modern style selected and a background color applied, the seconds block inherits the border radius from the custom style https://vertis.d.pr/ly0hcK
- [ ] I still can't make it fit on mobile, is there a specific way to do it?

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  I still can't make it fit on mobile, is there a specific way to do it?
> * [ ]  With modern style selected, i can change the separators width only by changing the border width, i don't know if this is expected

The block needs to fits with the default values. This is how it look on my part:

image
image
image

In Modern style, the separators are the right border of the elements. The border has been promoted as a glorified separator.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani @irinelenache Can you test the block? I added tablet and mobile support.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again, please let me know if i tested correctly

- [ ] The box width is still applied to the separators in frontend
editor: https://vertis.d.pr/K3SIzI
frontend: https://vertis.d.pr/8W3r5u

- [ ] If i change the settings for the desktop version, they are applied to the mobile version too until i change them. Shouldn't the mobile version have default values applied until the user wants to change them in some way?

- [ ] The selected colors are different in editor and frontend
editor: https://vertis.d.pr/gm02yQ
frontend: https://vertis.d.pr/2DaMVd

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, can you test again?

@HardeepAsrani, I removed the `styles` and introduced the `SizingControl` for the `border-radius`.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel You got me wrong there. You don't need to remove styles. They should be there but they should only inherit CSS styles from the file, not a change of attributes or inline CSS. Plus, they shouldn't be a Custom style. Every style should be able customized like normal.

**Comment by Soare-Robert-Daniel** [comment]
The style controls created many problems; I do not understand why the styles are overlapping in the class names. 

If I have 3 styles and selected them, all of them will be present in the block CSS.

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The box width is still applied to the separators in frontend
>   editor: https://vertis.d.pr/K3SIzI
>   frontend: https://vertis.d.pr/8W3r5u

Can you check if it is still happening?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 
As we talked, seems that the problem is happening on macOS with Google Chrome, related to some styling that shouldn't be applied https://vertis.d.pr/Fm7Vxx

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, we have an odd problem with the `"` on the CSS generator for PHP in Apple systems.

This `.wp-block-themeisle-blocks-countdown-container .wp-block-themeisle-blocks-countdown-display .wp-block-themeisle-blocks-countdown-display-component:not([name="separator"])` become `.wp-block-themeisle-blocks-countdown-container .wp-block-themeisle-blocks-countdown-display .wp-block-themeisle-blocks-countdown-display-component:not([name=\"separator\"])` which make the `name` selector to be invalid.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, I have refactored the selection mechanism. Can you test again on Apple stuff?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel
The box width is not applied to the separators anymore 👍 

- [ ] The border width is applied only in editor
- [ ] In frontend, the labels appear like Day, Hour, Minute, Second (https://vertis.d.pr/jmNwRK) instead of Days, Hours, Minutes, Second

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, I am once again asking for your technical expertise 😄

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Now the block seems to work fine 🚀 

The only problem that may occur is that an user has to make the mobile block smaller so it can fit on different screen sizes. For example, if the block looks like this on an Iphone X https://vertis.d.pr/rtqxBd , it will look like this on a narrow screen like Iphone 12 mini https://vertis.d.pr/dpE97X

**Comment by Soare-Robert-Daniel** [comment]
I think it will be fine if they use the WP mobile view to edit the block. -- GH CLI Comment﻿

**Comment by HardeepAsrani** [comment]
@irinelenache Mostly looks good. Two thing: remove the unused `style` attribute. Also fix the timezone, make sure website's time zone is being used even when we change. If you are unsure about the timezone, you can do the first and assign ping me to take over for that feature.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I finally found a way to deal with the timezones. Feel free to change it if it is not a good approach.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel What you've done wrong here is that you've underestimated the stupidity of how things work in Gutenberg: https://www.loom.com/share/75ecfe5c10d944aba3299ea1c03e38e7 - just take a look at the time and how it changes when you click on the same value. 😄 

Also, you shouldn't save the timezone in the attributes either. Nevermind all that, I'll take over this PR and see what happens.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel @irinelenache It should be fixed. Can you check to make sure the timezone now works properly?

**Comment by irinelenache** [comment]
@HardeepAsrani For me, this looks like it can be merged 👍

**Comment by HardeepAsrani** [comment]
Waiting for your heads up @Soare-Robert-Daniel when you're ready. 😄

**Pull request merged**
