### PR TITLE
WC Integration for the Review Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### TODO:

- [x] Get products raw data (using API Fetch)
- [x] Parse the raw data and map to attributes schema
- [x] Create the Inspector component

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you try using the Block Editor's Data API instead of Rest API?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you make sure that the WooCommerce product selector is a separate component? We will need that for https://github.com/Codeinwp/gutenberg-blocks/issues/734 too.

**Comment by Soare-Robert-Daniel** [comment]
If you suggest that the functions that extract the data from WC be independent, they are already. For the React component, it is not a big deal.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Basically the component should be something I can just add to any other block where it will display the list of WooCommerce products and selecting it will return the select product. This way I won't have to recreate the same thing and then keep them updated independently for other Woo-related blocks.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Let me know if everything works as you'd expect.

**Comment by Soare-Robert-Daniel** [comment]
Looks good 👍

**Comment by HardeepAsrani** [comment]
Hey @irinelenache, can you test this to make sure it all works fine? Details should be here: https://github.com/Codeinwp/gutenberg-blocks/issues/684

You need to have Neve Pro & WooCommerce for this to appear. Let me know how it goes or if you need any other info.

**Comment by irinelenache** [comment]
@HardeepAsrani Sure, tested and found a few things:

- [ ] If the product is discounted, the product review extracts only the final price
product info: https://vertis.d.pr/zJqQSn
product review: https://vertis.d.pr/bptWiF

- [ ] When single column style is selected, the review looks differrent in editor/frontend
editor: https://vertis.d.pr/ILIU2f
frontend:  https://vertis.d.pr/obScLi

- [ ] The style control isn't dynamically created like for a manual created review https://vertis.d.pr/5jmwmF

- [ ]  When i want to add a block, i get this error in console https://vertis.d.pr/3haiww

- [ ] If the title of the product contains special characters, they look like this in the select dropdown https://vertis.d.pr/DvsVBk (the title was **People 1 - edited**) 

- [ ] After i select the product desired, the block is loading until i click somewhere https://vertis.d.pr/3wl9Uc

- [ ] If the product is a variable product (https://vertis.d.pr/XPGFBv), the review shows only the smallest price   https://vertis.d.pr/2Z7C0Y

- [ ] If the product is out of stock, it is not reflected in the review

**Comment by HardeepAsrani** [comment]
@irinelenache It should be fixed. Three things:

- I can't reproduce the error. Can you give me more info?
- We decided to not highlight product out of stock.
- For the loading thing, I'll do it tomorrow so you can skip it.

**Comment by irinelenache** [comment]
@HardeepAsrani 
For the console error, i'm testing on Localwp, macOS 11.2.3 and Google Chrome, and the error occurs when i'm typing `/` in order to add a block

---

> The style control isn't dynamically created like for a manual created review https://vertis.d.pr/5jmwmF

This is still happening on my side

---

> If the product is a variable product (https://vertis.d.pr/XPGFBv), the review shows only the smallest price https://vertis.d.pr/2Z7C0Y

Now the review shows the price and discounted price for one particular variation in editor, and only the discounted price in frontend
editor: https://vertis.d.pr/Q6hrit
frontend: https://vertis.d.pr/xdtxgX

**Comment by HardeepAsrani** [comment]
> The style control isn't dynamically created like for a manual created review https://vertis.d.pr/5jmwmF

Can't do anything, that is automatically made. Works for me tho. But even if it doesn't, not in our control.

> Now the review shows the price and discounted price for one particular variation in editor, and only the discounted price in frontend

I think it's fine, we can later on improve the support for variation products in future. It's fine for now.

Thanks. Let's figure out the other issue with editor crashing so we can merge it. 🛩️

**Pull request merged**
