### PR TITLE
Accordion block v1

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
#### v0.9.0

- Remove the inline CSS from the `save` method

#### v0.8.0

- The icon is now clickable 

#### v0.70

- The content is now displayed using its full `height`
- Text can now be aligned 

#### v0.6.0

- Added PHP CSS file for `accordion`

#### v0.5.0

- Added PHP CSS file for `accordion-tab`

#### v0.4.0

- Added IDs to the `accordion` and `accordion-tab`
- Refactor some code

#### v0.3.0

- Added a new style for the icon
- Prevent some blocks to be used as content

#### v0.2.0

- The content of tabs are now general ( you insert a block )
- Some attributes were moved from the individual tabs to the parent

#### v0.1.0

- Add block;

### CODE REVIEW

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel tested it and found a few things:

- [ ] Clicking on the arrow doesn't expand the block, have to click only on text.
https://www.loom.com/share/673539780b65431184a562916a1ba1c8

- [ ] On narrow resolutions, the block is not complete on front-end (Galaxy fold as example)
https://www.loom.com/share/b6945305b3094a1ab66e7b6c68adbbd6

- [ ] Adding Highlight color to text doesn't work in front-end.
   editor: https://prnt.sc/urqoja
   front-end: https://prnt.sc/urqopw

- [ ] Adding some buttons and alligning them on center works only on front-end
https://www.loom.com/share/5f024765fae94d6880556da08b28f6f0

- [ ] The content doesn't support more than one bigger block
https://www.loom.com/share/1f8fec9d69944f31b64700e0a559536e

- [ ] Adding paragraph allignment doesn't work neither in editor or front-end
https://www.loom.com/share/92328506b7f64f5399aaf766e4332e3c

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] If i add an accordion block inside another, the child inherits the `Title background color` only in front-end
  Editor: https://prnt.sc/uu2sjg
  Front-end: https://prnt.sc/uu2sui

- [ ] If i add and delete the accordion block, somehow the block (or the section for it) still remains there until i click it and delete it again.
https://www.loom.com/share/be9fdb4522f14793b66af322cf7dee15
This is what i what it remains in the front-end after deleting it just once -> https://prnt.sc/uu2yvu

- [ ] Maybe this is related to the problem above: in editor, the block has two buttons for adding another accordion block (don't know if they are supposed to be there)

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel
> 
> * [ ]  If i add an accordion block inside another, the child inherits the `Title background color` only in front-end
>   Editor: https://prnt.sc/uu2sjg
>   Front-end: https://prnt.sc/uu2sui
> * [ ]  If i add and delete the accordion block, somehow the block (or the section for it) still remains there until i click it and delete it again.
>   https://www.loom.com/share/be9fdb4522f14793b66af322cf7dee15

You deleted the tab block and not the accordion, also if the accordion block does not have any tab, it will create one automatically. That is the cause

>   This is what i what it remains in the front-end after deleting it just once -> https://prnt.sc/uu2yvu
> * [ ]  Maybe this is related to the problem above: in editor, the block has two buttons for adding another accordion block (don't know if they are supposed to be there)

**Comment by HardeepAsrani** [comment]
Can you fix the remaining issues, if any, and change CSS generation to use the CSS Utility class like the rest of blocks? Thank you!

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani can you check if the css ( for accordion and icon list) works on frontend for this branch

**Comment by HardeepAsrani** [comment]
Is it done? I tried and it was pretty unusable.

**Comment by Soare-Robert-Daniel** [comment]
> Is it done? I tried and it was pretty unusable.

What are the wrong parts?

**Pull request closed without merging**
