### PR TITLE
Experiment/wp scripts

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Fix links in Review Block #686
- Fix block defaults not working in Default Section #685
- Allow Custom sizes in Posts Block #674
- Add filter to Posts Block's query: #569

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @irinelenache @Soare-Robert-Daniel,

Can you test this version? It fixes the above 4 mentioned issues + the general testing for the WordPress 5.8 Beta. I changed a lot of files so make sure everything works. Thank you! The branch to test is `experiment/wp-scripts`

**Review by Soare-Robert-Daniel — COMMENTED** [review]
For declaring the externals, we can use a webpack plugin from WordPress: `'@wordpress/dependency-extraction-webpack-plugin'`

Usage example: https://github.com/Soare-Robert-Daniel/gutenberg-blocks/blob/691a208c5fb6f3fcfd3b4ca9e2291d9c06d15028/webpack.config.js#L128-L131

**Comment by irinelenache** [comment]
@HardeepAsrani the fixes from this PR work fine 👍

**Comment by HardeepAsrani** [comment]
Thanks @Soare-Robert-Daniel! We could've saved a lot of time had we known about this sooner. XD

@irinelenache Have you tested it with WordPress 5.7 so make sure these changes don't crash pre-5.8 version? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani for me it works fine both with wp 5.7.2 and wp 5.8

**Pull request merged**
