### PR TITLE
Refactor column manipulation in Section Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Changelog
- allow moving & duplication on columns
- refactor old code

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, if we chose the initial layout through a variation picker, I do not think we can use the template library.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, @mghenciu  This is the design for our dilemma: 

image

@HardeepAsrani, I think the composition is key compared to injecting the button to the variation picker.

**Comment by mghenciu** [comment]
I would go for a more smooth approach, to not have 2 boxes (which may make the decision harder for users).
image

Or have a banner for Templates Cloud, to promote it.
image

**Comment by HardeepAsrani** [comment]
I didn't spend much time here but just to check, here's what you can do:

1. Remove the "Full" option as that is the default when you click on Skip.
2. Put the Variation picker inside the Placeholder that we used to have before.
3. Use CSS to remove Variation Picker Placeholder's borders and make things prettier.
4. You can center the Templates Library button and put the "OR" thing above that.

Make sure you remove the CSS used for the previous code and everything stays in SCSS files not inline.

Screenshot 2021-10-14 at 2 01 02 AM

**Comment by selul** [comment]
@Soare-Robert-Daniel the one suggested by Hardeep, i.e https://user-images.githubusercontent.com/2649903/137208306-093a54b5-4ac6-4260-a617-18c7e58cfea5.png looks better, we can use that one.

**Comment by Soare-Robert-Daniel** [comment]
Then I will drop this suggestion: `4. You can center the Templates Library button and put the "OR" thing above that.`

**Comment by HardeepAsrani** [comment]
Yea, it looked very weird that way. I'll add some CSS to improve some parts if possible. Thanks!

**Pull request closed without merging**
