### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Button Fixes
- Add Leaflet Map Block
- Fix Excerpt for Posts Block

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache & @Soare-Robert-Daniel - can you both test Otter + this repository to make sure everything is compatible with the upcoming WordPress 5.7?

You can install the Beta Tester plugin to get WordPress 5.7 RC1. Let me know if you need any help.

**Comment by Soare-Robert-Daniel** [comment]
In this version, the option to convert a reusable block back to a normal block is broken for our blocks.
It shows this error. 
image

Version 
image


@HardeepAsrani, @irinelenache  Can you confirm?

**Comment by Soare-Robert-Daniel** [comment]
## Bug List

> You can never trust JavaScript - S.R.D

### Logical
- [ ] Icon List doesn't send the new icon to its children with the `hasCustomIcon` property set to `false`. Code: https://github.com/Codeinwp/gutenberg-blocks/blob/dd0336fa898354456b6b642d766aa02e06993d1a/src/blocks/icon-list/item/edit.js#L117 Once the `attributes.library` is set at the initialization, that condition will never be `true` again.

### **Stay tuned for more.**

**Comment by HardeepAsrani** [comment]
> In this version, the option to convert a reusable block back to a normal block is broken for our blocks.
> It shows this error.

Seems to be an issue that will be fixed with Gutenberg before 5.7 release, as far as I can tell from discussions on there. But we will come back to it before 5.7 comes out.

Can you find anything else @irinelenache @Soare-Robert-Daniel? I'm hoping to release it on Wednesday if we can't get it sorted by then.

**Comment by irinelenache** [comment]
@HardeepAsrani i didn't find any problem with wp 5.7, do you have any more specific behaviours to test?

**Pull request merged**
