### PR TITLE
Release 1.5.3

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Store images locally when importing templates
- The improved template import mechanism
- Fix CSS file is not enqueued for posts outside the main loop
- Drop support for WordPress 5.3
- Add backward compatibility to Template Library import
- Fix category filter in Posts Section
- Add new Block Templates

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani 
- [ ] when inserting multiple templates one after the other, in a page, without saving it and refreshing the page, the upgrade notice duplicates each time
download (4)
- [ ] In WP 5.3, trying to add a Section returns this
download (5)
- [ ] Regarding "Fix CSS file is not enqueued for posts outside the main loop" the font family is still not loading, only the FA icons https://github.com/Codeinwp/neve-pro-addon/issues/668

**Comment by HardeepAsrani** [comment]
Fixed! Can you these again? @rodica-andronache THANK YOU!

**Comment by rodica-andronache** [comment]
@HardeepAsrani 
the Sharing Icons block throws this error in the editor 
download
Also, the error from using Section in WP 5.3.4 still persists. Not sure if you've meant to fix that too

**Comment by HardeepAsrani** [comment]
@rodica-andronache 
`the Sharing Icons block throws this error in the editor`

That's because the fix is in another directory. You can remove gutenberg-css folder from otter's vendor folder and replace it with github.com/Codeinwp/gutenberg-css/ to fix it.

And what Section error? Can you give more details?

**Comment by rodica-andronache** [comment]
@HardeepAsrani that fixed the issue with the Sharing Icons block.
For the other thing, I've meant this one that I've mentioned the first time:
In WP 5.3, trying to add a Section returns this
download (5)

**Comment by HardeepAsrani** [comment]
@rodica-andronache This release won't work below 5.4. We're making minimum WP version as 5.4. So you need to use older version in 5.3 and make sections and such, and then update to 5.4 with latest version to make sure the blocks are migrated nicely without any error. Sorry if it wasn't clear in the video. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani got it now, thanks. The migration worked well 👍

**Comment by HardeepAsrani** [comment]
Thank you! @rodica-andronache  😄

**Pull request merged**
