### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- WordPress 5.6 compatibility.
- Fix duplicate posts appear in Posts block when using WPML.
- Fox Sharing Icons block links.
- Improve Font Awesome Icons background.
- Fix Progress Bar percentage animation.
- Add ThemeIsle Icons to Buttons & Font Awesome Icons Block.
- Rename Font Awesome Icons Block to Icon Block.
- Add Circular Progress Block.
- Allow zero value for borderSize in Button Block.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @irinelenache - can you test this for the release? All the features are in the PR description. Let me know. 👍

**Comment by HardeepAsrani** [comment]
Make sure to test it with data coming from older versions of Otter & to also test with the latest beta version of WordPress.

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] Sharing Icons text has different color in customizer https://prnt.sc/vgtk5b and the links are underlined by default, until hovering (not sure if is the desired behaviour) https://prnt.sc/vgtkii

- [ ] Themeisle icons are visible only on front-end https://prnt.sc/vgtuye https://prnt.sc/vgtv6h

**Comment by irinelenache** [comment]
- [ ] Share doesn't work on linkedin, and get this error in console https://prnt.sc/vhb5a9

- [ ] Icon doesn't inherit the Icon color for hover state https://prnt.sc/vhbg2h https://prnt.sc/vhbia2

- [ ] Themeisle icons aren't well alligned in buttons https://prnt.sc/vhcatu

- [ ] When hovering a button that contains a Themeisle icon, if the color should change, the color of the icon changes before the color of the text. (Globe icon is from themeisle, Apple icon is from font awesome) https://www.loom.com/share/e3f0dcfe657442a982234038eb941f48

- [ ] Advanced Heading color control has no space between colors and title (happens to icon color controls too) https://prnt.sc/vhdshv https://prnt.sc/vheb5a

- [ ] Icon position control gets a bit cut when it's set to Right (happens to more controls that contain letters like g or y) https://prnt.sc/vhdvgn

Found no problems with WP 5.6 👍

**Comment by HardeepAsrani** [comment]
**===This is a work-in-progress comment which will be updated as I check more points===**

> Sharing Icons text has different color in customizer https://prnt.sc/vgtk5b and the links are underlined by default, until hovering (not sure if is the desired behaviour) https://prnt.sc/vgtkii

That's just the theme styles. We let themes to take control and design whatever the way they want.

**Pull request merged**
