### PR TITLE
Version 1.5.7

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Add Lottie Animations Block: https://github.com/Codeinwp/gutenberg-blocks/issues/413
- Add Progress Bar Block: https://github.com/Codeinwp/gutenberg-blocks/issues/388
- Prevent old custom CSS from being cached: https://github.com/Codeinwp/gutenberg-blocks/issues/418
- Fix Slider in Section's Vertical Alignment on AMP: https://github.com/Codeinwp/gutenberg-blocks/issues/375
- Tracking Data: https://github.com/Codeinwp/gutenberg-blocks/issues/321

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
> For Lottie, the first time you chose to Upload a file instead of Embed, you can't actually upload a file. The popup opens, and you can select a JSON, but the file doesn't get attached. To make it work, you need to save the post and refresh it. https://www.loom.com/share/20866dfe9d194dacacbcf1b9d27a3e89

Can you check again? It's working prefectly for me: https://www.loom.com/share/81e817021757453a956da8ed79798fec - I tried to reproduce it on both Firefox and Chrome.

**Comment by HardeepAsrani** [comment]
> For Lottie, the first time you chose to Upload a file instead of Embed, you can't actually upload a file. The popup opens, and you can select a JSON, but the file doesn't get attached. To make it work, you need to save the post and refresh it. https://www.loom.com/share/20866dfe9d194dacacbcf1b9d27a3e89

Can you check again? It's working perfectly for me: https://www.loom.com/share/81e817021757453a956da8ed79798fec - I tried to reproduce it on both Firefox and Chrome.

Update: Can you try to refetch and see if it works?

**Comment by HardeepAsrani** [comment]
> I couldn't test the Embed option for Lottie on my local. I think it's because of https, but I don't know how to do it. I've tried with https://assets4.lottiefiles.com/packages/lf20_8HVPGC.json and http://rodicaelena.com/wp-content/uploads/2020/09/31287-robot-playing-computer.json

Maybe you can try it on Jurassic Ninja? It works just fine on my Docker. I use this: https://assets4.lottiefiles.com/packages/lf20_8HVPGC.json - I sent a Jurassic Ninja instance to you on DM to test.

**Comment by HardeepAsrani** [comment]
```If I set up Loop ( for 2 times for example ) for Lottie, everything works well ( the animation happens 2 times ). But if I also enable Reverse, the looping doesn't happen anymore.```

Should work fine if you click outside and inside the block again. Can you try?

**Comment by HardeepAsrani** [comment]
> couldn't test the tracking option. No matter what template I inserted in a post, I couldn't see the option in the database, not sure if there's something I'm doing wrong

It was due to some uncommitted code. Can you try to re-fetch the otter-blocks folder and try again?

**Comment by HardeepAsrani** [comment]
> On a Lottie block, if I select Loop two times, a custom speed, and Reverse, the animation works well. But when I try to edit the post again, an error occurs https://www.loom.com/share/cfd873a245b04a8faceabe10ef4770f1

Fixed. Can you confirm on your side?

**Comment by HardeepAsrani** [comment]
> I couldn't find the option in Settings > Otter to get the Lottie block back to Embed from Upload.

Done. Added.

**Comment by rodica-andronache** [comment]
@HardeepAsrani 
- [ ] _For Lottie, the first time you chose to Upload a file instead of Embed, you can't actually upload a file. The popup opens, and you can select a JSON, but the file doesn't get attached. To make it work, you need to save the post and refresh it._

This is still happening for me. https://www.loom.com/share/bb72a356ab284946b80531af7cd65b67 This is happening just the first time you switch to Upload from Embed. From your video, I think you already had the block switched to Upload, so that might be the difference.

- [ ] _I couldn't find the option in Settings > Otter to get the Lottie block back to Embed from Upload._ 
Working well for me too now

- [ ] `If I set up Loop ( for 2 times for example ) for Lottie, everything works well ( the animation happens 2 times ). But if I also enable Reverse, the looping doesn't happen anymore.`
This is still happening for me, even if I click inside/outside the block. https://www.loom.com/share/b6f1e7f431e946d1a20081f40c76077e

- [ ] _On a Lottie block, if I select Loop two times, a custom speed, and Reverse, the animation works well. But when I try to edit the post again, an error occurs_
Working well for me too now

- [ ] _couldn't test the tracking option. No matter what template I inserted in a post, I couldn't see the option in the database, not sure if there's something I'm doing wrong_
Working well for me too now

**Comment by HardeepAsrani** [comment]
> This is still happening for me. https://www.loom.com/share/bb72a356ab284946b80531af7cd65b67 This is happening just the first time you switch to Upload from Embed. From your video, I think you already had the block switched to Upload, so that might be the difference.

Might be very hard to fix it. JSON upload isn't allowed and when we allow it using REST, it doesn't change the allowed files for the current editor instance. Do you think there can be a better alternative way?

**Comment by HardeepAsrani** [comment]
> Add a Progress Bar on a post that already has a Lottie block. The Progress Bar doesn't load entirely https://www.loom.com/share/f57a7aa4c5c34d93b6799999d577c6d5

> (this one was already mentioned on slack) If Duration for Progress Bar is set to 0, the percentage appears as NaN.

Can you try these two again also? Thank you!

**Comment by irinelenache** [comment]
> > Add a Progress Bar on a post that already has a Lottie block. The Progress Bar doesn't load entirely https://www.loom.com/share/f57a7aa4c5c34d93b6799999d577c6d5
> 
> > (this one was already mentioned on slack) If Duration for Progress Bar is set to 0, the percentage appears as NaN.
> 
> Can you try these two again also? Thank you!

@HardeepAsrani 

- [ ] If the post contains a lottie block and a progress bar that's **visible only after scrolling down**, when i refresh the page with **cleared cache**, the progress bar loads before i get to scroll and see it and with normal refresh it works fine.
(Tested it with other blocks instead of lottie and it works fine)
https://www.loom.com/share/8f62b831048740d1bfba0527eef24425

- If the duration of the Progress Bar is set to 0, the bar is instantly loaded with the desired percentage and got no errors.

- > For Lottie, the first time you chose to Upload a file instead of Embed, you can't actually upload a file. The popup opens, and you can select a JSON, but the file doesn't get attached. To make it work, you need to save the post and refresh it. 

   This happened to me also, but when i inserted the lottie animation with `Insert from URL` it worked fine without refreshing or doing something else.

- > If I set up Loop ( for 2 times for example ) for Lottie, everything works well ( the animation happens 2 times ). But if I also enable Reverse, the looping doesn't happen anymore.

  This is happening to me also, both in editor and front-end.

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] If i add a Progress bar and want to delete the Duration and add it manually, i get an error -> https://www.loom.com/share/0c436caf133241ce8ae98aeb9a8881e2
console error -> https://prnt.sc/udme72

- [ ] The Progress does a strange animation that's not easly observed if the page loads quickly. I could best replicate it when i set the percentage to 0.
https://www.loom.com/share/00d70509a0b843e0a07a8bbaa3fd2413

- [ ] If the Progress Bar has a semnificative Border radius set, the bar starts charging like it would be a bar with sharp corners. (Don't know if this is how it's supposed to work but thought it's worth mentioning)
https://www.loom.com/share/c4e4f8ec25554e6a8d8345e1e21faec2
   Can be seen on mobile too -> https://www.loom.com/share/84c59a4c5c244afa87561fd659e195a2 

- [ ] Adding a progress bar with the Title Style set to default, Border radius set to maximum and Duration set to 3 seconds, it can be seen that near the title's round corners, the background is darkened too. 
https://www.loom.com/share/4fcb67c103634f1c9ea8df97ada6ac84

- [ ] Lottie `Width` doesn't apply on front-end when `Trigger` is set to `Scroll`
https://www.loom.com/share/48d11b7043ad4484b2949be792698ed5

**Comment by HardeepAsrani** [comment]
Hey @irinelenache - can you test the ones I've marked as checked in your review to let me know if those still exist?

**Comment by irinelenache** [comment]
@HardeepAsrani the checked issues work fine now, but something else appeared.

- [ ] When i delete the duration time and try to enter it manually, the last value is written automatically when i type. If i try to enter a value bigger than 3 for the duration, 3 is entered as it's the biggest value, but then i can add another digit after it and make it 30.
https://www.loom.com/share/1edcf2f8e65547e09e6c658e1d72c001

**Comment by irinelenache** [comment]
The Progress bar appears to be ok, only a few mentions:

- [ ] When Title style is set to default, and percentage is lower, it looks different in editor and front-end.
Editor -> https://prnt.sc/ueu7vv
Front-end -> https://prnt.sc/ueu89v

- [ ] When adding an **animation** to the block, the animation and charge of the progress bar start **concomitant**, and makes it a bit confusing. If i set the animation delay to one second and progress block duration to one second, when the block appears it is already charged. 
Maybe the progress bar charge should wait for the animation delay **or** for the animation delay and animation duration.
https://www.loom.com/share/1d6d839628874f2bbe6f82632431fc9c

**Comment by HardeepAsrani** [comment]
> When adding an animation to the block, the animation and charge of the progress bar start concomitant, and makes it a bit confusing. If i set the animation delay to one second and progress block duration to one second, when the block appears it is already charged.
> Maybe the progress bar charge should wait for the animation delay or for the animation delay and animation duration.
> https://www.loom.com/share/1d6d839628874f2bbe6f82632431fc9c

We can skip this, for now, seems not that important. Rest is done, I suppose @Soare-Robert-Daniel?

**Comment by HardeepAsrani** [comment]
This is for @Soare-Robert-Daniel - I saw few issues: https://www.loom.com/share/5b618b083d084f11994e3dd8539494a1

- [ ] During "append," the percent should have a default color of white.
- [ ] Add title/percent color options.
- [ ] If you try to set height with keyboard, clamp takes place and we're screwed.

**Comment by Soare-Robert-Daniel** [comment]
> 
> 
> This is for @Soare-Robert-Daniel - I saw few issues: https://www.loom.com/share/5b618b083d084f11994e3dd8539494a1
> 
>     * [ ]  During "append," the percent should have a default color of white.
> 
>     * [ ]  Add title/percent color options.
> 
>     * [ ]  If you try to set height with keyboard, clamp takes place and we're screwed.

Only Duration and Percentage have the clamp function. In the height case, the minim value is 10, so if you put a number which is smaller than 10, the range control will change it with 10 the cursor will also remain so that the next key pressed will add the digit to 10. Even if you delete all the numbers, the range control will put 10 automatically.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] When Percentage is set to Outer, it doesn't have the selected color in front-end.
editor: https://prnt.sc/ufelxq
front-end: https://prnt.sc/ufem7l

**Comment by rodica-andronache** [comment]
@HardeepAsrani tested all the issues again, and the two things still happen for me:
- [ ] If I set up Loop ( for 2 times for example ) for Lottie, everything works well ( the animation happens 2 times ). But if I also enable Reverse, the looping doesn't happen anymore.

https://www.loom.com/share/b6f1e7f431e946d1a20081f40c76077e

- [ ] When I delete the duration time and try to enter it manually, the last value is written automatically when I type. -> this happens for all fields of that type, not just for Duration

https://www.loom.com/share/1edcf2f8e65547e09e6c658e1d72c001

**Comment by HardeepAsrani** [comment]
> If I set up Loop ( for 2 times for example ) for Lottie, everything works well ( the animation happens 2 times ). But if I also enable Reverse, the looping doesn't happen anymore.

Not really able to reproduce it, so will skip it for now.

> When I delete the duration time and try to enter it manually, the last value is written automatically when I type. -> this happens for all fields of that type, not just for Duration

It's how it works if it has a minimum/maximum value.

**Pull request merged**
