### PR TITLE
Map Block

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### To Do 

- Edit
    - [x] Initialize the map
    - [x] Add map to page
    - [x] Add an ID to the block
    - [x] Resize the block's height using the mouse
- Inspector 
    - [x] Add location
    - [x] Add marker
    - [x] Add marker when click on location
    - [x] Add location search
    - [x] Add zoom and height
    - [x] Enable/Disable other component for control
    - [x] Transform from Google Maps in Map and vice versa
- Save
    - [x] Add data 
    - [ ] Better hand gesture for mobile
- Frontend
    - [x] Add function to load attributes into the page 
    - [x] Add function to parse the data 
    - [x] Add functions to create & modify the map
    - [x] Enable/Disable zoom controls
    - [x] Enabe/Disable dragging
    - [x] Add AMP
- Utility
    - [x] Add function to make a location request
    - [x] Add function to parse the response

### For the next version:

- Add custom icon marker

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  I got a very big problem. Check this: https://operations.osmfoundation.org/policies/nominatim/ . I can't make the search behave like in the Google Map Block. Also, I think Nominatim ban my IP for breaking the policy. My computer can't access the API anymore (at least for today, i will check tomorrow).

So ideally, we need to make a request per second. Right now, the block search the GPS coordinates every time when the user introduce a location and update the map (like in the google map block), which is wrong way to to it according to the policy.

Should I implement a search button for pressing after the user insert the location and a message to try again if the location was not found?

**Comment by HardeepAsrani** [comment]
I was reviewing the block and got some feedback:

- Width of the map in the editor seemed to be bit off. It should take entire width of the container.
Screen Shot 2021-02-12 at 4 12 35 AM

- In Google Maps, if you click a marker in the Map, it will automatically open that field in the Inspector sidebar.

- Instead of a search button, it should just search on pressing enter. You can mention the same in control with `help` attribute.

- There should be a marker button in the map so people can easily place their marker and move it. It's not easy for everyone to find the long/lat, and not every place is searchable.

- Same goes for changing map location, it should change when dragged.

- Make sure to write a migrate for both maps, so people can switch from one map to another. And if someone migrates to Google Map & they haven't added an API, give the option in the placeholder to migrate back to this one.

- Add a delete marker button in the marker popup.

- Lat/lang should be string, not int. They were int in Google Map too but there were some issues we later faced and then decided to convert it to a string.

For the Frontend part, you should give it a try. I'm always happy to take over and do it but I'd really like you to get used to it:

It will be a dynamic block so save function will return null like this: https://github.com/Codeinwp/gutenberg-blocks/blob/0815d2fc940f4a535e3ccf4da61cc7cc4603f9c4/src/blocks/google-maps/index.js#L33

And then in the render part of the block, we just dump all the attributes to a global variable array: https://github.com/Codeinwp/gutenberg-blocks/blob/0815d2fc940f4a535e3ccf4da61cc7cc4603f9c4/inc/render/class-google-map-block.php#L124-L130

And once we have that, we just use JS to render the map: https://github.com/Codeinwp/gutenberg-blocks/blob/master/src/frontend/google-map/index.js

The frontend part is pretty much done in JS too, we just use PHP to render the placeholder and dump all the attributes.

And if this map provider or API gives an iFrame option, we can just use that to display it to AMP: https://github.com/Codeinwp/gutenberg-blocks/blob/master/inc/render/class-google-map-block.php#L99-L110

Let me know If you need any help there. If after all that you can't do it, I can always take over. 😄

**Comment by Soare-Robert-Daniel** [comment]
Made some of the suggestions. I will see what I can do about the frontend

**Comment by HardeepAsrani** [comment]
Great. Make sure you add an ID first.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache can you please check this block on this branch to see if everything is alright?

After changing to this branch, in the main otter folder `otter-blocks` in `/plugins` run the command `composer dumpautoload -o` to make sure that PHP will load the PHP files associated with the block.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] With this setting deactivated https://prnt.sc/103m48m , the zoom controls ( + and - ) aren't there, but the map can still be zoomed by mouse wheel scrolling.
- [ ] When i try to move the Marker, this happens ( https://www.loom.com/share/2dc1a863a6044981b61ba1a25c5c0dcd ), it affects only the editor and if i click everywhere on the map, those labels disappear
- [ ] After adding a description to a marker, the text input control gets empty until refreshing the page https://www.loom.com/share/b4ac8323efc045a5b6a8a39cdd7544b6

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel
> 
> * [ ]  With this setting deactivated https://prnt.sc/103m48m , the zoom controls ( + and - ) aren't there, but the map can still be zoomed by mouse wheel scrolling.

This is fine. The option disable only the button. It is the same behavior as in `Google Maps`.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel regarding the Google maps:

- [ ] Pegman shouldn't be visible here? https://prnt.sc/103nt47
- [ ] If i drag the Pegman for Street view, i can't escape opening it. I tried dragging outside the map, using right-click but street view is still opening

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel regarding the Google maps:
> 
> * [ ]  Pegman shouldn't be visible here? https://prnt.sc/103nt47
> * [ ]  If i drag the Pegman for Street view, i can't escape opening it. I tried dragging outside the map, using right-click but street view is still opening https://www.loom.com/share/122a61342a6b4cbebe92c9ca029102f6

No idea about the **correct** behavior of that block.  @HardeepAsrani can answer those questions.

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel
> 
> * [ ]  When i try to move the Marker, this happens ( https://www.loom.com/share/2dc1a863a6044981b61ba1a25c5c0dcd ), it affects only the editor and if i click everywhere on the map, those labels disappear
> * [ ]  After adding a description to a marker, the text input control gets empty until refreshing the page https://www.loom.com/share/b4ac8323efc045a5b6a8a39cdd7544b6

@irinelenache, can you recheck those?

**Comment by HardeepAsrani** [comment]
> Pegman shouldn't be visible here? https://prnt.sc/103nt47

Google API issue, nothing we can do.

> If i drag the Pegman for Street view, i can't escape opening it. I tried dragging outside the map, using right-click but street view is still opening https://www.loom.com/share/122a61342a6b4cbebe92c9ca029102f6

Same, not in our control.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel i rechecked those issues, now they work fine 👍 
Found another thing, when using **both maps** into a **2 column section** the maps align different even if they have the same height.
Editor: https://prnt.sc/104onx7
Frontend: https://prnt.sc/104oonx

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel i rechecked those issues, now they work fine 
> Found another thing, when using **both maps** into a **2 column section** the maps align different even if they have the same height.
> Editor: https://prnt.sc/104onx7
> Frontend: https://prnt.sc/104oonx

@irinelenache, can you recheck it?

**Comment by irinelenache** [comment]
> > @Soare-Robert-Daniel i rechecked those issues, now they work fine
> > Found another thing, when using **both maps** into a **2 column section** the maps align different even if they have the same height.
> > Editor: https://prnt.sc/104onx7
> > Frontend: https://prnt.sc/104oonx
> 
> @irinelenache, can you recheck it?

@Soare-Robert-Daniel  Rechecked it and not it works fine 👍

**Comment by HardeepAsrani** [comment]
Great work @Soare-Robert-Daniel - only two issues + one addition:

- If you add the block to a page and then scroll the page, the scroll gets caught in the map which is an issue people used t complain about maps in past. Can you fix it for this?
- Can you add an option to drag to change the height as we have in Google maps?
- Last, if you have two blocks and the top one is Maps, the block control of the second block get hidden inside the first:

Screen Shot 2021-02-25 at 6 00 55 PM

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
As mentioned in the comments.

**Comment by Soare-Robert-Daniel** [comment]
> * If you add the block to a page and then scroll the page, the scroll gets caught in the map which is an issue people used t complain about maps in past. Can you fix it for this?

Found a workaround on this problem. Also, check this alternative: https://github.com/elmarquis/Leaflet.GestureHandling

> * Can you add an option to drag to change the height as we have in Google maps?

Done.

> * Last, if you have two blocks and the top one is Maps, the block control of the second block get hidden inside the first:

Added margin on the bottom of the block.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This is how it looks when I add the block to editor using Firefox.

Screen Shot 2021-02-26 at 6 18 30 PM

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel This is how it looks when I add the block to editor using Firefox.

@HardeepAsrani can you check again?

**Comment by HardeepAsrani** [comment]
z-index is still an issue. Is this something that can be solved or that's how it will be?

Screen Shot 2021-02-27 at 1 10 45 AM

**Comment by Soare-Robert-Daniel** [comment]
Hard to tell. To make some space you need to use `margin` property and find the magic number.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel That's not the way to do it. Have you tried playing with its z-index value?

**Comment by Soare-Robert-Daniel** [comment]
No. I did not change the Leaflet's CSS code.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, can you check in mobile mod if the block ask to use `two fingers` for dragging?

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel the block asks for the two fingers use, and zooming/moving through map works fine 👍 . tested with iphone 11

**Pull request merged**
