### PR TITLE
Add Circular Progress

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
#### v0.10.0

- Remove inline CSS from the `save` method

#### v0.9.0

- Handle the situation when the height is 0

#### v0.4.0 * 2 = v0.8.0

- Added PHP file
- Added `id` for block 

#### v0.7.2

- Fixed the `font-size` scaling when the defaults are `undefined`.

#### v0.7.1

- Fixed the `font-size` for the bottom style of the `title`

#### v0.7.0

- Added the option to set the `font-size` for the title in the inspector.
- the SVG will not be generated if the `radius` of the circles is negative or 0;

#### v0.6.0

- On the frontend, the SVG is now rendered using Javascript.
- Added `to` and `from` to `progress-bar`.
- Readjusted the `font-size`.
- Changed the block `icon` to `rotateRight`

#### v0.5.0

- `Circular Progress Bar` ->` Circle Counter`.
- Added the option the place the `title` under the `circle counter`.

#### v0.4.1

- Fix the thickness of the circle.

#### v0.4.0

- Replaced `TextControl` with `RichText` for the `title` property.

#### v0.3.0

- Added the possibility to transform the block into `progress-bar-block` and reverse.
- New Inspector design.
- Added `font-size` as standalone property for the percent value.

#### v0.2.3

- Set the same limits for `ResizableBox` and `RangeControl` of the `height`.
- Added `width` property to the `ResizableBox `of the `height ` .

#### v0.2.2

- Changing block `height` will keep the` percentage` proportion in the editor.

#### v0.2.1

- Set the `text-align` for Title as `center`.
- Set the` width` of the container the same as the `height`.
- Added flexbox to `.wp-block-themeisle-blocks-circular-progress-bar`.

#### v0.2.0

- Code Refactor - cleaned some old code.

#### v0.1.0

- Add block.

### CODE REVIEW

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] On mobile, the title is not centered when it goes multiline.
desktop -> https://prnt.sc/uis8i7
mobile -> https://prnt.sc/uis8yt

- [ ] When adding a section with 3 columns, each one with a max height circular progress bar block, and neve has sidebar activated, the blocks intersect in front-end.
https://www.loom.com/share/ba51c6bf55c64225862ec4e5df4638d1

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] Changing block height doesn't keep percentage proportion in editor.
https://www.loom.com/share/ffafcaa2165844278085701fe17b7984

- [ ] Changing the height without using the Height control doesn't work exactly as expected. (don't know if this is a problem or not)
https://www.loom.com/share/8e22319a2c8546fdadccbda25db591d4

> When adding a section with 3 columns, each one with a max height circular progress bar block, and neve has sidebar activated, the blocks intersect in front-end.

This still happens if the content width is lowered in customizer.
https://prnt.sc/ujksp7

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] The title and the progress bar intersect.
https://prnt.sc/ul5zly

- [ ] Circle thickness doesn't work now
https://www.loom.com/share/dc88145b46c64dd9a945df7f8c89f451\

> Changing the height without using the Height control doesn't work exactly as expected. (don't know if this is a problem or not)
 Changing block height doesn't keep percentage proportion in editor.


These are fixed now 👍

**Comment by HardeepAsrani** [comment]
- [ ] Transform `from` should be in the respective blocks, instead of just in Circular block.
- [ ] Default font-size should be in CSS, not attributes.
- [ ] Use `rotateRight` icon for the block.
- [ ] I'll suggest you render the SVG using JS in front-end because in past we used SVN in save and it caused some issues.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The only problem that i could find:

- [ ] when i set the font size to max value and percentage to 100%, the number gets out of the circle no matter how thick the circle is. (This also happens with lower percentages and bigger circle thickness)

https://prnt.sc/umecf9

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] now the font size title works **only on front-end** when the title is set to appear on the bottom
https://www.loom.com/share/cd933cb33d344d228abdfca24d3929e6

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel One more thing I found: https://www.loom.com/share/14b6ddb9526f43f585e6cc6ba0ca2688?from_recorder=1

- If you add the block and remove it while an animation is ongoing, console gets lightup. We should unsubscribe to event listeners to avoid this.

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
