### PR TITLE
THE FUTURE IS NOW

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
## Feature

- TypeScript - ‘da propa tool ta fix fings an' stuff
   - **Finally, we have `autocomplete` options**
   - No more undefined variables
   - No more magic based on hopes
   - No more hacky way to write code 
- The last version of Babel Eslint Parser -- Betta an hard

### Converted blocks - can be used for learning how to make the transition.

- Plugin Card
- About Author
- Pricing
- Services
- Testimonials

**Stay tuned for more**.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Will this affect our current workflow? Is it gonna apply to the entire plugin?

**Comment by Soare-Robert-Daniel** [comment]
No. It is a completely separate setup. You can see in the `webpack` that the TypeScript has its own loader - which means two things: it will not interfere with JavaScript files and is not allowed for the moment to use other non-typescript files. Our js files will use babel like before, nothing changed in this matter. Also, TypeScript forms a separate js bundle, named for the moment: 'blocks-v2.js' -- and strongly suggest keeping this structure. 

TypeScript should be used for future blocks since they are independent most of the time. Going from TypeScript back to JS is a very straightforward method: you delete all the types. TypeScript is a superset of JS, which means JS code is a valid TypeScript code but vice versa is not true. So, if we migrate the olds blocks, we need only to put date types like `number, string, string[], ...`, and if you want to turn back you just have to remove what have you added.

At first, it might be hard to get used to the types, but after you taste their power there is no turning back.
I recommend this short introduction: https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html
For types: https://www.typescriptlang.org/docs/handbook/basic-types.html

The only thing that affects the current Js file is the new version of `babel-eslint` named [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser). The `babel-eslint` has been deprecated and the Babel team recommend the new version in https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint

P.S: We can be the first people who can write articles about migrating Js code to TypeScript in WordPress :+1: .

**Comment by HardeepAsrani** [comment]
Got it. Seems pretty good so far. You can even convert some old blocks to it, many of our blocks are very simple, like Plugin Card, Testimonials, and such, instead of having the "Brand new World" block. Make sure to test everything to see it works at least from WordPress 5.4.

**Comment by Soare-Robert-Daniel** [comment]
The future will have to wait.

**Pull request closed without merging**
