### PR TITLE
Add Popup Block

### PR DESCRIPTION
**Pull request by HardeepAsrani**
This adds a Popup Block to Otter. If one is using this block with Neve Pro then it will show limited options. The disabled Pro feature only appears if one has the Neve theme activated.

Can you review @irinelenache @Soare-Robert-Daniel?

You can also take a look @abaicus to see if everything seems okay.

CLoses: https://github.com/Codeinwp/gutenberg-blocks/issues/768

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested it, overall it looks nice 🚀  found only a few issues:

- [ ] The spacing between elements is different in editor and frontend
editor: https://vertis.d.pr/A9if51
frontend: https://vertis.d.pr/gyCF3u

- [ ] The **Display interval** setting that appears when **Dismiss for recurring visitors** is activated, can't be changed by sliding https://vertis.d.pr/VLRu4Z

- [ ] The popup doesn't look ok on mobile
desktop: https://vertis.d.pr/qGmneV
mobile: https://vertis.d.pr/0Ge2dx

**Comment by HardeepAsrani** [comment]
It should be fixed. @irinelenache - can you confirm?

**Comment by irinelenache** [comment]
@HardeepAsrani Tested again, the reported issues are fixed, found only something small:

- [ ] On mobile, the popup header padding is trimming the content https://vertis.d.pr/6npWhg (It happens on desktop too, but it's no that obvious)

**Comment by HardeepAsrani** [comment]
That doesn't seem like an issue as everything looks good on my side. Anyway, we can leave it as it's only padding.

**Pull request merged**
