### PR TITLE
Version 1.5.4

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Button Group Improvements: https://github.com/Codeinwp/gutenberg-blocks/issues/328
- Fixed Caption field missing from Slider Block: https://github.com/Codeinwp/gutenberg-blocks/issues/372
- Image management in Slider & Gallery Block: https://github.com/Codeinwp/gutenberg-blocks/issues/373
- Fix issue with CSS inline loading twice
- Fix Posts Block offset bug: https://github.com/Codeinwp/gutenberg-blocks/issues/376
- Remove default font size from Posts Block

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani I still have some things to test for tomorrow but here's what I've seen so far:

- [ ] The border radius and border width dissappear in the editor after you refresh it https://www.loom.com/share/cf78cfc8ed424aaeaf3237814c2d8130

- [ ] When I activated the Gutenberg plugin and visited a post I’ve created before with Otter blocks ( slider, buttons group ) I got these notices https://www.loom.com/share/0d25ef788ed746f9bc7adc3a0ddbe774

- [ ] When the Gutenberg plugin is installed, in the editor, the line height doesn’t apply to the buttons that have only icons https://prnt.sc/tq2lgr. On frontend, it does https://prnt.sc/tq2m18
 
Regarding https://www.loom.com/share/22bd75903b994848b24215a5fc625435 - I couldn’t see it, is there something else I need to get from git? Thanks

**Comment by HardeepAsrani** [comment]
```When I activated the Gutenberg plugin and visited a post I’ve created before with Otter blocks ( slider, buttons group ) I got these notices https://www.loom.com/share/0d25ef788ed746f9bc7adc3a0ddbe774```

I can't reproduce it. Can you try it in a new instance? If not, can you send the debug log for this error so I can see if it traces back to any Otter files?

**Comment by HardeepAsrani** [comment]
`When the Gutenberg plugin is installed, in the editor, the line height doesn’t apply to the buttons that have only icons https://prnt.sc/tq2lgr. On frontend, it does https://prnt.sc/tq2m18`

It works fine. Can you see if you're using the latest version of Gutenberg, as I think there was a new verison recently.

**Comment by rodica-andronache** [comment]
@HardeepAsrani I've done testing everything I could think of, besides the new control for animations as I can't see it. Let me know how I can get that.

When I activated the Gutenberg plugin and visited a post I’ve created before with Otter blocks ( slider, buttons group ) I got these notices https://www.loom.com/share/0d25ef788ed746f9bc7adc3a0ddbe774 -> I've managed to replicate this on a different instance (from two that I've tested), but I'm not sure if is related to Otter or not. I'm attaching the log file
[debug.log](https://github.com/Codeinwp/gutenberg-blocks/files/4993976/debug.log)


When the Gutenberg plugin is installed, in the editor, the line height doesn’t apply to the buttons that have only icons https://prnt.sc/tq2lgr. On frontend, it does https://prnt.sc/tq2m18 -> Yes, I'm using the latest version of Gutenberg. I was able to replicate this again, by first creating a post with the Button Group block, and changing all their properties ( color, font, line-height etc ). After that I activated Gutenberg, and in the editor, the line height does not apply to buttons that have just icons, anymore.

**Comment by HardeepAsrani** [comment]
@rodica-andronache 

> I've managed to replicate this on a different instance (from two that I've tested), but I'm not sure if is related to Otter or not. I'm attaching the log file

I wasn't able to reproduce it. Do we have an intern in Q/A or someone to take a second look to make sure?

> Yes, I'm using the latest version of Gutenberg. I was able to replicate this again, by first creating a post with the Button Group block, and changing all their properties ( color, font, line-height etc ). After that, I activated Gutenberg, and in the editor, the line-height does not apply to buttons that have just icons, anymore.

Can you please make a video of it? I wasn't able to reproduce it.

For the Animations, you can clone this https://github.com/Codeinwp/gutenberg-animation/tree/development to `otter-blocks/vendor/codeinwp` and then run npm install & npm run build inside the folder.

**Comment by irinelenache** [comment]
> I wasn't able to reproduce it. Do we have an intern in Q/A or someone to take a second look to make sure?

I couldn't replicate both problems, they worked on my machine.

**Comment by rodica-andronache** [comment]
@HardeepAsrani tested again and I think both issues are related to the `Posts` block while Gutenberg is installed.
In this video, you can see the notices appearing when I use the Posts block with Gutenberg installed https://www.loom.com/share/f488b33494f642ae8144a53bb642dc79
And here, you can see the line-height not applying to the buttons that have just an icon, when there is also a posts block in the post https://www.loom.com/share/b869af89ef1846918fc51da569a76de6
I hope this is helpful

**Comment by HardeepAsrani** [comment]
@rodica-andronache The first seems to be an issue with Gutenberg and will be fixed in the next release, nothing to do with us but a nice catch!

**Comment by HardeepAsrani** [comment]
The second issue also seems to be related to that, CSS not loading or something. We can see it later if it happens with the next update of Gut.

**Comment by HardeepAsrani** [comment]
@rodica-andronache can you test this https://github.com/Codeinwp/gutenberg-animation/tree/development? It's the last thing, I promise. 😄

**Comment by rodica-andronache** [comment]
@HardeepAsrani couldn't spot any issues with the animations, neither on wp 5.4, with/without Gutenberg or wp 5.5 beta 👍

**Pull request merged**
